### ISSUE TITLE
change branching model

### ISSUE THREAD

**Issue by superbock** [CPJKU/madmom#105]
Although never really stated somewhere, we followed (more or less) this branching model: http://nvie.com/posts/a-successful-git-branching-model/

I'm in the process of preparing version 0.13 release and I'm running into some problems:

* If we want to be `master` the current version we should merge the `release/0.13` (which is branched from `develop`) into `master`.
* This would create a rather massive merge, which I don't like

While looking for a solution to this situation, I found this blog post: https://barro.github.io/2016/02/a-succesful-git-branching-model-considered-harmful/ and must say that I much prefer the "cactus model" over the "nvie" one.

I don't agree/care about the merge commit issue, I think it's fine the way it is, but the other points are valid. Thus I propose the following:

* Rename the `develop` branch to `master`

For releases we add the following rules:

* Release branches start off from `master` and use a `release/` prefix
* When ready, they are tagged and left as they are
* Dotreleases (everything with two dots in the version, e.g. 0.12.1) start off from the release branches
* Relevant changes are back-ported to `master` (by cherry-picking?)

For development of features or fixes we add these rules:

* Create development branches from `master`
* Use whatever naming scheme you like (except `release/`), but we can continue to use `feature/` and `fix/`
* Rebase your features on `master` before you create a pull request
* To fix issues, amending, rebasing squashing is allowed
* Since feature branches are allowed to be rebased, never start other branches off them

This should simplify stuff a lot.

Any thoughts?

**Comment by fdlm** [comment]
I don't see the problem of "large merges" from develop to master. Since master should not have changed between releases, the merges should be straight-forward.

The change you are advocating here is basically
 1. rename 'develop' to 'master', and 
 2. for releases instead of merging back to a release branch creating a new branch for each minor release.
 3. never branch of any branch other than 'master'

I'd be fine with this.

**Comment by superbock** [comment]
Set the `master` branch to be the default branch, and removed the old `develop` branch.
