### ISSUE TITLE
add CNN functionality

### ISSUE THREAD

**Issue by superbock** [CPJKU/madmom#117]
@f0k has working numpy-only CNN code which should be added to `madmom.ml.nn.layers`.
If this is in place we can add CNN based reference algorithms, e.g. the ICASSP 2014 onset paper and the structural segmentation stuff of @f0k and @grrrr.

**Comment by f0k** [comment]
Note that my code is not fully compatible with your layers. It applies a CNN to a sequence of overlapping spectrogram excerpts, but avoiding any redundant convolutions. To do so, it propagates lists of arrays corresponding to the different offsets introduced at each layer that pools over time and reunites them in the end.
