### ISSUE TITLE
What parameters were used to generate stereo_sample.notes in the tests?

### ISSUE THREAD

**Issue by Aerlinger** [CPJKU/madmom#17]
When applying the `PianoTranscriptor` script to the `tests/data/stereo_sample.wav` sample I get note predictions much different than those currently present in the `tests/data/stereo_sample.notes` file. I'm wondering if the `tests/data/stereo_sample.notes` was generated by a human hand? If not it may be helpful to provide a concrete example as it seems some of the documentation for the scripts in /bin is sparse and out of date. 

I'd be pitch in and help in updating some of the documentation if it's useful to others.

**Comment by Aerlinger** [comment]
Also, considering the annotation files support comments, it might actually be useful to output a human readable header comment at the top of the file containing metadata about the parameters and algorithm which generated the note/onset file.

**Comment by superbock** [comment]
None of the supplied onsets/notes/beats annotations were generated by an algorithm, they are considered ground truth informations, either manually annotated or taken directly from MIDI files. IIRC, the `tests/data/stereo_sample.notes` annotations are generated form MIDI ground truth.

Good point of adding additional information into a comment, will do so (after having double checked the source of the ground truth).

**Comment by superbock** [comment]
Added description to the files, see commit 243ec60.

Can you elaborate on what you mean by sparse/outdated documentation in `/bin`? (please not that I fixed some minor inconsistencies in commit d575476)
