### ISSUE TITLE
ImportError: No module named TempoDetector

### ISSUE THREAD

**Issue by linsion1** [CPJKU/madmom#19]
when i run : python TempoDetector single test.wav
the error come up,some logs is:
  File "D:\Program Files\WinPython-64bit-2.7.10.3\python-2.7.10.amd64\lib\multip
rocessing\forking.py", line 489, in prepare
    file, path_name, etc = imp.find_module(main_name, dirs)
ImportError: No module named TempoDetector

please help thx

**Comment by superbock** [comment]
Please post problems regarding the installation of the package to the mailing list (https://groups.google.com/d/forum/madmom-users). When doing so, please provide the full error log, not just part of it.

**Comment by superbock** [comment]
There was a thread on the mailing list (https://groups.google.com/forum/#!topic/madmom-users/WelNop0FVCs), and James figured out how to get it installed on Windows. I put the information on the WIKI (https://github.com/CPJKU/madmom/wiki/Install-on-Windows).
