### ISSUE TITLE
Unable to access madmom.audio.cepstrogram

### ISSUE THREAD

**Issue by waissfowl** [CPJKU/madmom#203]
I think it was forgotten in the corresponding file `__init__.py` (I just added it and it worked fine after that)

**Comment by superbock** [comment]
It was not forgotten. Unfortunately, this module is not thoroughly tested yet, and the API may change as well. This is the reason we don't import it by default right now. I hope to address the issues together with #42. In the meantime you can import the needed classes via `from madmom.audio.cepstrogram import ...`

**Comment by superbock** [comment]
Closing, since #269 addresses this. MFCCs will be included in next release.
