### ISSUE TITLE
Check for file handles in audio.signal.load_audio_file

### ISSUE THREAD

**Issue by flokadillo** [CPJKU/madmom#220]
`audio.signal.load_audio_file(filename, ...)` checks if the input is a filehandle using `if not isinstance(filename, str)`. However, if _filename_ is represented as type _unicode_, this condition is true as well and we therefore conclude that the variable is a file handle and try to close the file, which results in an error.
Therefore, I suggest it would be safer to check for file handles using
`if hasattr(filename, 'read')` or `if isinstance(filename, file)`.

**Comment by superbock** [comment]
You have to be careful, Python 3 does not have a `unicode` type, just `str`. Maybe just use a `try/except`.
