### ISSUE TITLE
install_requires in setup.py?

### ISSUE THREAD

**Issue by jorgehatccrma** [CPJKU/madmom#222]
Thanks for providing this package, it's awesome.

I noticed that you don't specify `install_requires` in the `setup()` call in `setup.py`. Instead, you rely on the user manually adding dependencies (numpy, scipy, nose and cython). Is there any strong reason to do this? While these dependencies are fairly common, it is not ideal to have to rely on the user. Plus, it potentially breaks setuptools-based installation of packages that depend on madmom. According to [Python Packaging User guide](https://packaging.python.org/), you should be using [install_requires](https://packaging.python.org/distributing/#install-requires):

```
setup(...
    install_requires = [
        numpy,
        scipy,
        cython,
        nose,
    ]
```

This way you can even require minimum versions, E.g.:

```
setup(...
    install_requires = [
        numpy>=1.11,
        scipy,
        cython>=0.24,
        nose,
    ]
```

Cheers!

**Comment by superbock** [comment]
You're right about everything. Now we rely on users to have the requirements given in [`requirements.txt`](https://github.com/CPJKU/madmom/blob/master/requirements.txt) (with the indicated minimal versions) or install them manually. Although this can be done quite easily with `pip install -r requirements.txt` your suggestion might be easier.

**Comment by jorgehatccrma** [comment]
Another advantage of using `install_requires` is that if a third party develops a package that specifies madmom as a dependency in their own `setup.py`, then setuptools will make sure to install madmom's dependencies before installing madmom. If, on the other hand, there's no `install_requires` in madmom, then there's no way to make sure dependencies are installed before madmom. Even of this hypothetical third party package do specify madmom's dependencies as its own dependencies, setuptools doesn't guarantee order if dependency installations, so the installation may crash.
