### ISSUE TITLE
Cython 0.25 breaks build

### ISSUE THREAD

**Issue by giubil** [CPJKU/madmom#225]
When building madmom (or installing via pip) with Cython==0.25, it won't build and produce the following message : 

`creating build/lib.macosx-10.12-x86_64-3.5/madmom/ml
clang -bundle -undefined dynamic_lookup -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk build/temp.macosx-10.12-x86_64-3.5/madmom/ml/hmm.o -o build/lib.macosx-10.12-x86_64-3.5/madmom/ml/hmm.cpython-35m-darwin.so
building 'madmom.ml.nn.layers' extension
error: unknown file type '.pxd' (from 'madmom/ml/nn/layers.pxd')`

The same error is generated when building on Linux

**Comment by superbock** [comment]
I don't have a proper fix for this issue at the moment, but I will look into it as soon as possible (but this might take two weeks).

A workaround for now is to simply remove the 'madmom/ml/nn/layers.pxd' file completely. It is there to cythonize the `ml.nn.layers` module to give a speed-up for recurrent networks and is not needed for madmom to work.

**Comment by superbock** [comment]
This is of course complete nonsense. Instead, `setup.py` needs to be adjusted to not build a shared `madmom.ml.nn.layers` object. Sorry for the confusion.

**Comment by giubil** [comment]
Or, the other workaround I have for now, is juste to fix the version of Cython in the requirements.txt file like this `Cython==0.24`

Maybe you could change the requirements.txt while you find a permanent fix ?

**Comment by superbock** [comment]
Yes, good point. We should probably integrate this workaround into #222.

**Comment by superbock** [comment]
Cython reverted the change that made the build break (https://github.com/cython/cython/commit/4ecdd3e4e5984011fe93af6c4ccaf6d67a88f6f5). Will look into how to adapt to the new extension build system.
