### ISSUE TITLE
Use peak_picking directly on spectrogram, possible?

### ISSUE THREAD

**Issue by carlthome** [CPJKU/madmom#228]
First of all, love madmom. It's a wonderful package. :dancer: 

I'm wondering if it's possible to use the peak detector in 2D, e.g. on spectrograms? I'm asking because I noticed that if the input to `peak_picking` is a 2D ndarray the output is a tuple, but I can't make much sense of the output unfortunately and I've failed to find any documentation of this.

My current idea is to just detect peaks individually in each dimension, and then cluster the peaks with k-means or something, but surely that would be suboptimal.

**Comment by superbock** [comment]
Regarding the output format, it is exactly the same as returned by `np.nonzero()` (https://docs.scipy.org/doc/numpy/reference/generated/numpy.nonzero.html).
In case of 1D signals only the first item of the tuple is returned.

So yes, it should be possible to use it on a spectrogram directly. However I am not sure if the output is the one you're expecting. You should get peaks in time for each frequency bin individually -- not sure if this is what you meant by "detect peaks individually in each dimension" or not.

HTH

**Comment by carlthome** [comment]
Ah, very cool! :tada: 

Not really what I'm after, though. I guess some smoothing and a filterbank could work, but I'm looking more for blob detection with shape constraints, or something (close frequency bins should _probably_ be thought of as a single fundamental but maybe not always). [These three](http://scikit-image.org/docs/dev/auto_examples/plot_blob.html) alternatives seem like an okay starting point.
