### ISSUE TITLE
Proper handling of state-ful processors

### ISSUE THREAD

**Issue by superbock** [CPJKU/madmom#237]
RNNs, HMMs, CRFs and the like have to keep their state when being processed in streaming mode, since their next output depends on the previous output.

As initially discussed in #230, it is a bit tricky to have all of the following properties/behaviours:
- [x] offline processing should not change at all
- [x] existing models should not be altered
- [x] if being called twice with the same input in offline mode, the results must be identical
- [x] streaming mode must take care of buffering in a way that does not alter offline processing

There are a couple of approaches to handle this:
1. try to handle everything in the ``process()`` method
2. have a separate method for online processing, e.g ``process_online()`` 
3. add extra buffer handling methods to streaming capable classes and call them only in streaming mode, i.e. via ``processors.process_online()`` function.

Right now, I tend towards 2. or 3. (they are basically equivalent) since 1, requires a lot of if/elif/else statements and handling of previously unavailable attributes.

**Comment by superbock** [comment]
This issue is addressed by the following individual PRs:

- #243 for RNNs
- #244 for HMMs

Right now, we agreed on using two separate methods, namely `process_step()` and `process_sequence()` to be called by `process()` if there must be a distinct behaviour for online/offline mode.

For CRFs, I am not entirely sure, but it seems that we don't have a forward path for CRFs anyways, so I guess this will not be done anytime soon. @fdlm, any comments?

So we can close this issue as soon as #243 and #244 are merged.

**Comment by fdlm** [comment]
We have two CRF implementations in madmom: the specialised one for the `CRFBeatDetector`, and a general one for `DCChordRecognition` and `CNNChordRecognition`. Both implement only the Viterbi algorithm.

I don't think this will change soon - the forward path would only be necessary if any of the algorithms could be run in online mode, but

 - the `CRFBeatDetector` needs to know the length and the tempo of the song, so cannot operate in an online setting, and
 - for the chord recognition algorithms we would need to check if and how much computing the forward path using a CRF would improve results compared to using the neural networks alone (and my guess is not that much).

I thus think we can close this issue.

**Comment by superbock** [comment]
Closing, since #243 and #244 are merged.
