### ISSUE TITLE
Extend the bar-pointer model to handle two parallel observation probabilities 

### ISSUE THREAD

**Issue by georgid** [CPJKU/madmom#251]
I am doing a note-transcription algorithm which is based on top of the bar pointer model (e.g. the state space is combination of the BarStateSpace and another NoteStateSpace). The note states emit a separate 1-dimensional pitch feature, which means essentially that there are two parallel observation models: the current using SpectralFlux and the other one using pitch.   

I modified [the line](https://github.com/CPJKU/madmom/blob/master/madmom/ml/hmm.pyx#L429) to `def viterbi(self, bar_observations, note_observations):` 

Since Viterbi is called [here](https://github.com/CPJKU/madmom/blob/master/madmom/features/beats.py#L1598) I need to modify the `in_processor` called [here](https://github.com/CPJKU/madmom/blob/master/bin/GMMPatternTracker#L125) to return not only the spectral flux but also another observation sequence of my other feature: pitch.

Can I have the in_processor return return two observations sequences?
 
A workaround  is extending the MultiBandSpectrogramProcessor to return a third dimension, but that is not very elegant...

**Comment by superbock** [comment]
I'm not sure if I understand your problem correctly. E.g. I am not sure if this is more of a question on how to accomplish something or more of a feature request to support some wanted functionality. A description of what you're trying to accomplish or even better a code example would definitely help :)

You can't just modify [line 427 of `hmm.pyx`](https://github.com/CPJKU/madmom/blob/master/madmom/ml/hmm.pyx#L429) without changing the code inside `viterbi()`. And you haven't stated how these two observations are handled internally. I am also not sure how two observation models can be combined to infer a single state sequence. Anyways, it is highly unlikely that the `viterbi()` method will be altered to support your modified calling convention and I strongly advise against changing this basic functionality. Almost certainly this is not the correct place to incorporate additional functionality.

Usually, the state space defines some sort of mapping from state numbers to the meaning of these states. This has per se nothing to do with a HMM, it is just to provide an interpretation of the state numbers. Examples can be seen in [features.beats_hmm](https://github.com/CPJKU/madmom/blob/master/madmom/features/beats_hmm.py).

The transitions between these states are handled by a `TransitionModel`, and the mapping from observations to (log-)densities by the `ObservationModel`. Both are then used by the `HMM` class to infer the best state sequence by either the Viterbi or the forward algorithm.

So what you basically want (or at least what I think that you want) is a single state space which models (i) whatever you use from the `BarStateSpace` as well as (ii) the additional pitch information. Then you have to define custom transition and observation models which can be given to the `HMM` class. No need to change the `viterbi()` method (which would break a lot of code BTW).

Regarding your question if you can have "the in_processor" (or any other processor) return two observation sequences (or two whatever): yes of course. Just create your own processor which either returns an array with an additional dimension, a tuple or a list. Processors are just take some sort of input data, process it, and return the processed data. There a plenty of examples, where processors return more than a single value/array/thing/whatever.

HTH

**Comment by georgid** [comment]
Hi, Sebastian, thanks a lot for your pointers and comprehensive answer. 
It is a question, not a feature request.
Yes, I have another hidden state for a musical note (having *three* state labels: attack, sustain and release of a note).  The model can be seen here: 
https://drive.google.com/file/d/0B4bIMgQlCAuqV0hxNXE2cFkzNWc/view?usp=sharing

So to extend the bar-pointer model there are two steps:
1. extend the state space
2. extend the observation model to handle two probabilities simultaneously
In my previous question I jumped to step 2. I will not modify the `viterbi() ` itself. I will do a custom observation model. It is clear to me.

Now I have a question to step 1: 
I need to build a single custom state space `BeatNoteStateSpace`, which  is a Cartesian product of the `BeatStateSpace` and a  `NoteStateSpace` that has the 3 states listed above. Essentially, I will replicate  each of the [state_positions](https://github.com/CPJKU/madmom/blob/master/madmom/features/beats_hmm.py#L92 ), `state_intervals`, `first_states`, `last_states` 3 times (for the 3 states of `NoteStateSpace`)   :
 e.g. state positions [0.02 0.04 0.1 ...]  will become [0.02 0.02 0.02 0.04 0,04 0,04 0.1 0.1 0.1 ...]
So I know that state 0 is attack, state 1 is sustain, 2 is release, 3 is attack, 4 is sustain etc. Then `BeatNoteStateSpace` will be combined  just the same way as it is now to form the new `BarNoteStateSpace`. Do you see anything thaht might break in the decoding of bar positions [here](https://github.com/CPJKU/madmom/blob/master/madmom/features/beats.py#L1616) or in some other step if I implement the new state this way?

Also, do you know if s.b. has extended the state space in madmom already in a similar way - e.g. with a new hidden state? Conceptually similar state space has been used for example already in[ this paper](http://www.mtg.upf.edu/system/files/publications/Holzapfel_TrackingTheOdd_0.pdf). They have addioonal state for a rhythmic pattern, but they did their code in matlab. Maybe you know if in some of the forks of madmom  a similar state space was already implemented ?

**Comment by superbock** [comment]
Ok, things are getting clearer now. Still, I have some questions/remarks...

1. Extending an existing state space might not be the best solution. In the linked PDF doc it is stated that there are a total of N=207 notes with 3 states (attack, stable pitch, non-vocal) each. These are 621 states. As you correctly state, your resulting state space is a cartesian product these states and the beat states, this would result in a rather large state space (3.5M states in case of beat state space, and an insane 16M if you later on extend this also to bars with 3 and 4 beats per bar).

2. Why should it break decoding [for the PatternTrackingProcessor](https://github.com/CPJKU/madmom/blob/master/madmom/features/beats.py#L1616)? It is not using any of your classes.

3. The cited Holzapfel paper uses a similar (if not exactly the same) DBN as in [Krebs 2013](http://www.cp.jku.at/research/papers/Krebs_etal_ISMIR_2013.pdf) which is part of madmom already, implemented as [PatternTrackingProcessor](https://github.com/CPJKU/madmom/blob/master/madmom/features/beats.py#L1439)

4. I think that you're best advised to design both your state space and as well as the transition and observation models from scratch, especially given the immense number of states if you simply extend an existing state space. Try to keep them in the range of thousands, not millions.

HTH

**Comment by georgid** [comment]
Sorry for not giving the full picture in the beginning, here it is. 

> 1. Extending an existing state space might not be the best solution. In the linked PDF doc it is stated that there are a total of N=207 notes with 3 states (attack, stable pitch, non-vocal) each. These are 621 states. As you correctly state, your resulting state space is a cartesian product these states and the beat states, this would result in a rather large state space (3.5M states in case of beat state space, and an insane 16M if you later on extend this also to bars with 3 and 4 beats per bar).

The note state space might have quite a number of states, true. (in fact, in the [note model](matthiasmauch.de/_pdf/mauch2015computeraided.pdf)  there are 69 distinct pitches with 3 states = 207 states in total ). This  however has very precise pitch resolution and covers about 2 octaves.   Depending on the music style, it can be reduced ( for example, using octave-wrapping etc.) to the order of ~50 states. So this would result, combined with the current ~1400 states per beat, to around 70 K states per beat and 2-3 M per bar. 
 


> 2. Why should it break decoding for the PatternTrackingProcessor? It is not using any of your classes.

I mean that I aim to modify some of the state space members ( state_positions, state_intervals, first_states, last_states) of the current `BeatStateSpace` in a way that does not affect the beat-specific pointers.  Then I would plug the new custom state space into the PatternTrackingProcessor - without modifying it - with the intention that it can track the tempo and bar position without breaking the current tracking mechanism. (of course it will have on top information about the note state)

Let me restate the question: Do you see anything place in the code (for example in [decoding](https://github.com/CPJKU/madmom/blob/master/madmom/features/beats.py#L1616) ), where the modified state space variables (however modified in the careful way, described above) this might introduce a problem?

> 3. The cited Holzapfel paper uses a similar (if not exactly the same) DBN as in Krebs 2013 which is part of madmom already, implemented as PatternTrackingProcessor

The Holzapfel paper uses the same DBN as Krebs 2013, true. It has one modification though: the rhythmic pattern is not one per song, but there are 2 or more rhyhtmic patterns for the same metrical cycle. E. g. there is an additional hidden variable - rhythmic state - with  pattern state space  1 < |R| = < 10.  so if I were to implement this paper in madmom I would do a new state space, which is a cartesian product of the existing Beat State Space with |R|. Since this is more or less the same I want to do, I was wondering  if you are aware of s.b. having extended the state space in madmom already in a similar way - e.g. with a new hidden state? If yes, I could reuse some implementation strategies. 

As a matter of fact, reproducing [ the Holzapfel paper](http://www.mtg.upf.edu/system/files/publications/Holzapfel_TrackingTheOdd_0.pdf) is a necessary step of my ultimate model, but for now I keep things simple,  e.g. R=|1|. 

Thanks!

**Comment by superbock** [comment]
I think that point 4 of my last comment is the most important one. You should really consider this. If you want to build your stuff on top of existing classes, just go ahead. But you should *definitely* not try to alter existing classes.

Some more comments on your points (using the same numbering):

1. As a side note, the number of states I am referring to is with the (more efficient state space proposed in [Krebs 2015])[http://www.cp.jku.at/research/papers/Krebs_etal_ISMIR_2015.pdf]. This paper also gives numbers for memory consumption and computation time. A 4-minute song with 50 frames per second has 12,000 frames. If you want to track/model only beats (i.e. 70k states) you must remember ~840M state ids to perform Viterbi decoding. This requires ~3.3GB memory. If you want to track a whole bar (i.e. 2M+ states), you must remember 24G state id, which requires ~200GB memory (24G does not fit int uint32 any more, so you have to use uint64). Unless you have a very big machine and lots of time to wait for the computations to finish, you *really* should consider point 4 ;)

2. You should not alter any of the `BeatStateSpace` attributes at all, otherwise it *will* break existing code. The only way to reuse existing classes is to add additional attributes, e.g. some mapping from state ids to your note states (attack, stable pitch, non-vocal). However, I think you're better of designing your own state space rather than extending an existing one... i.e. point 4. ;)

3. I am not entirely sure, but Section 4.1.2 states: "In this paper we allow transitions only between patterns of the same rhythm class, which will force the system to assign a piece of music to one of the learned rhythm classes.". This sounds to me as that there's only one rhythmic pattern per song, isn't it? I think the reason for this is simply the size of the state space (and the ability to do inference in finite time). If you don't allow transitions between rhythmic patterns, you can simply build individual state spaces for each pattern, do inference on all of them individually and choose the one with the highest log-likelyhood. I did exactly this for the `DBNDownBeatTracker`, i.e. model each bar-length individually and then choose the most appropriate one. I also reduced the number of modelled tempi and allowed tempo changes only at bar level in order to keep the number of states and transitions as low as possible to get everything computed within finite time.

Again, I still think that you're best advised to design your own state space from scratch instead of extending an (already quite big) state space to contain even more states. And keep the number of states as low as possible, preferably <<100k.

HTH

**Comment by georgid** [comment]
I did [commit](https://github.com/georgid/madmom/tree/4014f41b42fdc8202f179f04eea973990bc5978f
) a version with another hidden state for musical Note, which means new joint state space, cartesian product of the   BarStateSpace and [NoteStateSpace](https://github.com/georgid/madmom/blob/4014f41b42fdc8202f179f04eea973990bc5978f/madmom/features/bar_notes_hmm.py#L20).

If the note states are in the order of 50-100, the joint state space is in the order of <<100k, and has computationally acceptable speed. 
Can be run by the [extractor](https://github.com/georgid/madmom/blob/4014f41b42fdc8202f179f04eea973990bc5978f/bin/GMMNotePatternTracker)
  

Short description in the beginning of the README file. (more can be provided on demand)
It is meant to be generic and reusable if somebody ever wants to extend the bar pointer model with additional hidden state.
