### ISSUE TITLE
ImportError: cannot import name comb_filters

### ISSUE THREAD

**Issue by georgid** [CPJKU/madmom#259]
Running` python madmom/bin/GMMPatternTracker single path_to_file.wav
`
results in 

Traceback (most recent call last):
  File "madmom/bin/GMMPatternTracker", line 12, in <module>
    from madmom.processors import IOProcessor, io_arguments
  File "/Users/joro/workspace/madmom/madmom/__init__.py", line 23, in <module>
    from . import audio, evaluation, features, ml, models, processors, utils
  File "/Users/joro/workspace/madmom/madmom/audio/__init__.py", line 27, in <module>
    from . import signal, ffmpeg, filters, comb_filters, stft, spectrogram
ImportError: cannot import name comb_filters

**Comment by superbock** [comment]
Looks like the C-extensions are not compiled or could not be found. Did you follow the installation instructions at http://madmom.readthedocs.io/en/latest/installation.html? And how did you install it, from package or source?

**Comment by georgid** [comment]
From source. Ahhh, yes, I forgot the installation step. Thanks.
