### ISSUE TITLE
Spectrul flux vs median deviation 

### ISSUE THREAD

**Issue by siryog90** [CPJKU/madmom#264]
Hello,

I notice in the you have changed the way you compute positive differences in the Mel filterbank in comparison to your paper from 2011. Seems you no longer look at the deviations from the median, but rather utilize flux.
Would this affect the results from 2011 or should I go ahead with the median deviations?

Also, 
Could you tell me what the difference is in the BEATS_BLSTM models? 
Cheers

**Comment by superbock** [comment]
Gonna close this, since it is not an issue.
