### ISSUE TITLE
MIDI tempi list handling bug?

### ISSUE THREAD

**Issue by rainerkelz** [CPJKU/madmom#271]
hi, I believe in 
[midi.py, line 1506](https://github.com/CPJKU/madmom/blob/f5725c680498735eb55af69928409f2753b71546/madmom/utils/midi.py#L1506)

the line should be changed from
`if tempi is None:`

to

`if len(tempi) == 0:`

(it can never be `None` after line 1503)

**Comment by superbock** [comment]
Yes, this is a leftover from 52a2ae8. Did you run into any problems?

I think the right solution id to unify the two following if conditions into one:

`if len(tempi) == 0 or tempi[0][0] > 0:`

**Comment by rainerkelz** [comment]
yeah, i was a tiny bit surprised :)

given line 1503 the second check is unnecessary, `if len(tempi) == 0` is sufficient ...

i'm confused about line 1509 and 1510 too... why this insert?

**Comment by superbock** [comment]
MIDI requires a tempo to be set, otherwise it can't determine the exact location of the events occurring before the first tempo event. To prevent such an undefined behaviour we insert a tempo event at the very first tick. So I think the or-clause is safer to use.
