### ISSUE TITLE
AppVeyor ffmpeg download: Not found

### ISSUE THREAD

**Issue by SebastianPoell** [CPJKU/madmom#288]
Hi,

AppVeyor tries to download ffmpeg-2.7 and fails because the version 2.7 does not exist (anymore):
https://ffmpeg.zeranoe.com/builds/win64/shared/

![screen shot 2017-05-17 at 11 22 28](https://cloud.githubusercontent.com/assets/1398398/26147225/2a25d280-3af3-11e7-8cdd-6745affcb310.png)

I think that can easily be fixed by using another ffmpeg version in appveyor.yml. E.g:
```
- ps: Start-FileDownload ('http://ffmpeg.zeranoe.com/builds/win' + $env:PYTHON_ARCH + '/shared/ffmpeg-latest-win' + $env:PYTHON_ARCH + '-shared.7z' ) ffmpeg-shared.7z
```

Regards, Sebi

**Comment by superbock** [comment]
PR welcome :)
