### ISSUE TITLE
replace MIDI code

### ISSUE THREAD

**Issue by superbock** [CPJKU/madmom#306]
Since we now have online streaming capabilities, it is time to replace the current MIDI code with something capable of MIDI streams. Our current code is based on [Python-midi](https://github.com/vishnubob/python-midi) which hasn't seen an update within almost 3 years and is not compatible with both Python 2 and 3.

[Mido](https://github.com/olemb/mido) seems to be a good choice, since it is actively maintained and used by many other projects. It offers streaming capabilities and is compatible with both Python 2 and 3.

Hopefully a change also resolves #271 and #192.

**Comment by fdlm** [comment]
Will the new code be compatible with the old interface? If not, we should provide a reasonable deprecation timeline.

**Comment by superbock** [comment]
Right now there is no plan to remove the old code too soon, simply because there is no need to.

The new code is more or less compatible to the old one. The only thing I changed is that `notes`, `tempi` and `time_signature` are now properties instead of methods. Changing the unit (i.e. seconds, ticks or beats) can now be done by changing the `MIDIFile.unit` instead of passing the unit to the function.

I think the old way was ok, but didn't like it too much, so it seems to be a good time to think about an API change when refactoring everything. More details about what changed/will change in #308.
