### ISSUE TITLE
Zero Padding in STFT not implemented

### ISSUE THREAD

**Issue by fdlm** [CPJKU/madmom#317]
From the `madmom.audio.stft.stft()` docs:
```
    fft_size : int, optional
        FFT size (should be a power of 2); if 'None', the 'frame_size' given
        by `frames` is used; if the given `fft_size` is greater than the
        'frame_size', the frames are zero-padded, if smaller truncated.
```
However, I don't see zero-padding implemented in the function. Accordingly, this does not work:
```
    def test_zero_padding(self):
        results = stft(sig_2d, window=None, fft_size=sig_2d.shape[1] * 4)
```
Or did I miss something?

**Comment by superbock** [comment]
Good catch! 51f3b5e052af9592d6753c4ecb7b29233ab57780 fucked the whole thing up. The fix is really simple, though: simply change [line 119 of stft.py](https://github.com/CPJKU/madmom/blob/master/madmom/audio/stft.py#L119) to `data[f] = fftpack.fft(fft_signal, fft_size, axis=0)[:num_fft_bins]`.
