### ISSUE TITLE
Unify behaviour of load functions.

### ISSUE THREAD

**Issue by fdlm** [CPJKU/madmom#338]
Currently, load functions (`load_beats`, `load_chords`, ...) do not all accept the same type of parameters. For the sake of consistency, we should unify this. This will also make them easier to use.

We need to define what each `load_*` function accepts, while keeping in mind that the `*Evaluation` classes should be usable with files, file handles, and directly passed detections.

Here is my suggestion:

 - `load_*` functions *only* accept files or file handles. They are called "load" functions for a reason.
 - Checking whether something is a file (and thus `load_*` needs to be called) or a detection instance should be done within the `__init__` methods of the evaluation classes.

Ping @superbock :smile:

**Comment by superbock** [comment]
Your proposal sounds reasonable. I think adding this to #313 makes sense, since this PR bundles the i/o functions at a central place.

**Comment by fdlm** [comment]
Yes! Can you rebase #313 onto the current master, then I'll take care of the chord and key functions.
