### ISSUE TITLE
Is normalization during the computation of features necessary?

### ISSUE THREAD

**Issue by siryog90** [CPJKU/madmom#354]
@superbock How crucial do you think is the normalization of the stft window and the normalization of the triangular filters during the computation of the feature vector (Nx120)?

Can't we just subtract the mean from the feature vector and divide by the std before we give it to the neural networks?

**Comment by superbock** [comment]
It is not too crucial, but it is a very simple way to have the values in a pre-defined range.

Normalisation of the STFT window makes sure that all STFTs have the same value range, independently of the type of the input signal (i.e. it doesn't matter if your input signal is 16 bit int or 32 bit float).

Normalisation of the filters is a simple counter-measure against over-emphasising higher frequencies (where more frequency bins are summed) if logarithmically spaced filters are used.

Of course you can normalise to zero-mean and unit variance as well, and this will most definitely perform equally well if the features are fed into a neural network. However, these measure are quite crucial for simple signal-processing-based methods (e.g. SuperFlux) to perform well and on signals of various input types.

HTH
