### ISSUE TITLE
madmom.audio.signal.Stream stores only hop_size of data to each frame_size frame

### ISSUE THREAD

**Issue by Mikkoeinari** [CPJKU/madmom#355]
### Expected behaviour

The Stream should read hop_size chunks from the input and store them to hop_size buffers.

### Actual behaviour

The Stream reads hop_size chunks from the input and stores them to frame_size buffers.
The hop_size must be same as the frame_size in order for the stream to work correctly.
The frame_size should be removed from Stream altogether, or be utilized correctly.

```python
self.stream = self.pa.open(rate=self.sample_rate,
                                   channels=self.num_channels,
                                   format=pyaudio.paFloat32, input=True,
                                   frames_per_buffer=self.hop_size,
                                   start=True)
 # create a buffer
self.buffer = BufferProcessor(self.frame_size)
```
changing to  following would fix the behaviour:
```python
self.stream = self.pa.open(rate=self.sample_rate,
                                   channels=self.num_channels,
                                   format=pyaudio.paFloat32, input=True,
                                   frames_per_buffer=self.hop_size,
                                   start=True)
 # create a  buffer 
self.buffer = BufferProcessor(self.hop_size)
```
### Steps needed to reproduce the behaviour

```python
import madmom

for i in madmom.audio.signal.Stream(sample_rate=44100, num_channels=1,frame_size=2048, hop_size=441):
    print(i[-460:-420])
    break

```

[  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   4.23995167e-04
   2.61035340e-04   1.59418953e-04   2.27797136e-04   7.20366486e-04
   5.92413533e-04   5.37052343e-04   5.34271589e-04   3.27483838e-04
   3.74124240e-04   2.24088202e-04  -7.37750961e-05  -1.37939889e-04
  -1.67490653e-04  -9.70183974e-05  -1.02720478e-04  -3.78943776e-04
  -3.87339416e-04  -4.36287228e-04  -4.58635768e-04  -3.28312395e-04]

**Comment by superbock** [comment]
I am pretty sure that everything works as expected (although we don't have tests for the `Stream` class yet).

The general idea (very similar to `FramedSignal`) is that a signal is split into overlapping frames of length `frame_size` and two adjacent frames are `hope_size` samples apart. I.e. there is a certain overlap in the signal contained in two consecutive frames.

I am not sure what you are trying to accomplish exactly, but setting `hop_size = frame_size` results in a stream without overlapping frames.

Does this make sense?

**Comment by Mikkoeinari** [comment]
For some reason i only get hop_size of data /frame if i use different hop_size.
Maybe i don't understand how to use the iterator properly. I just get frames that have zeros and hop_size of data in them.

**Comment by superbock** [comment]
Yes, this is expected. Via `frame_size` you set the length of the (overlapping) frames. E.g. if you want to compute a STFT with 2048 samples of data you need to set `frame_size` to 2048.

Then the next frame will be ready as soon as `hop_size` new samples are available. The internal buffer is shifted by this size and the new data is appended. For the given example with a `hop_size` of 441, two adjacent frames are always 10ms apart and contain 2048-441=1607 samples of common data. For the first frame in your example these are all zeros since the buffer was initialised with zeros.

As said in my previous comment, simply setting `hop_size = frame_size` will result in non-overlapping frames and your first frame will not contain any zeros (unless the input is zeros of course).

**Comment by Mikkoeinari** [comment]
I think i figured it out finally. It was the first few iterations where the frame was not yet filled with data that was causing me problems.

The issue can be closed.
