### ISSUE TITLE
local key detection function

### ISSUE THREAD

**Issue by bzvew** [CPJKU/madmom#362]
If a song changes its key, can madmom detect those local keys instead of a global key?

**Comment by fdlm** [comment]
No, the current models cannot do that out of the box.

You can make them output frame-wise predictions if you want (it requires a bit of hacking), and work with these to try to find local keys, but these predictions can be quite noisy. You will need to use a sliding average window of some length to get meaningful outputs. You will need to do some experiments to find a good window width.

To make the models output local predictions, you need to delete the `AverageLayer` from the model files. 
This layer basically just averages the predictions over the whole song. You could do this by modifying the `CNNKeyRecognitionProcessor` accordingly.

**Comment by fdlm** [comment]
I guess this can be closed, then.
