### ISSUE TITLE
KeyRecognition Missing from pip install build

### ISSUE THREAD

**Issue by djmoffat** [CPJKU/madmom#369]
### Expected behaviour

I expect that every single executable program included with madmom would be presented within the pip install

### Actual behaviour

When I installed madmom, using pip, the following executables are present in /usr/local/bin - KeyRecognition is the only one missing...

2to3
BeatDetector
BeatTracker
CNNChordRecognition
CNNOnsetDetector
CRFBeatDetector
ComplexFlux
DBNBeatTracker
DBNDownBeatTracker
DCChordRecognition
GMMPatternTracker
LogFiltSpecFlux
MMBeatTracker
OnsetDetector
OnsetDetectorLL
PianoTranscriptor
PickleProcessor
SpectralOnsetDetection
SuperFlux
SuperFluxNN
TempoDetector

### Steps needed to reproduce the behaviour

```
pip install numpy scipy cython
pip install madmom
ls /usr/local/bin
```

### Information about installed software

Please provide some information about installed software.

```
sys.version '2.7.15 (default, May  5 2018, 03:32:06) \n[GCC 4.9.2]'
madmom.__version__ '0.15.1'
np.__version__ '1.14.3'
scipy.__version__ '1.1.0'
```

**Comment by superbock** [comment]
Key detection functionality was not available when 0.15.1 was released. It will be included in the next release (0.16) which will be release soon. Until then you have to install from source to use key detection functionality.
