### ISSUE TITLE
Downbeat issue

### ISSUE THREAD

**Issue by bzvew** [CPJKU/madmom#372]
I run the following code:
act_downbeat = RNNDownBeatProcessor()(music_audio)
proc = DBNDownBeatTrackingProcessor(beats_per_bar=4,fps=100,observation_lambda=300)
beat_times = proc(act_downbeat)

on this file, and the downbeat it finds is wrong. Is there a way to improve that? The first beat is downbeat, but it think the second is. Also what's the reason for that issue?
[ET-no_vocal.mp3.zip](https://github.com/CPJKU/madmom/files/2212209/ET-no_vocal.mp3.zip)

**Comment by superbock** [comment]
There's not much you can do about — except training your own model. It is hard to tell what the exact reason is, but a highly probable reason might be that it the network thinks that the "snare" should be on either beat 2 or 4.
