### ISSUE TITLE
Broken offline tempo estimation via DBN 

### ISSUE THREAD

**Issue by SebastianPoell** [CPJKU/madmom#375]
### Expected behaviour

Estimating the offline tempo via DBN should work.

### Actual behaviour

Hi, seems like there is a bug when estimating the tempo **offline** via **DBN**, resulting in error messages and incorrect tempo estimations.

The reason is that the activations get smoothed inside the TempoEstimationProcessor, which improves the results for `method=acf` and `method=comb` but breaks the DBN when `method=dbn` is used:

```python
act_smooth = int(round(self.fps * self.act_smooth))
activations = smooth_signal(activations, act_smooth)

```

Why? Smoothing can lead to activations > 1. When computing the log densities for the DBN, an observation greater than 1 means that the logarithm of a minus-number is calculated, which results in minus infinity and breaks the Viterbi algorithm:

```python
log_densities[:, 0] = np.log((1. - observations) / (self.observation_lambda - 1))

```

### Solution

One solution would be to normalize the activations after smoothing, but results turned out to be better if smoothing is simply not applied at all for `method=dbn`.

Therefore, one suggestion would be that we remove the smoothing from TempoEstimationProcessor and move it directly into CombFilterTempoHistogramProcessor and ACFTempoHistogramProcessor. I could do a small PR on that if you like ;)

### Steps needed to reproduce the behaviour

Just use `method=dbn` for the tempo detector and try it on some activations in offline mode.

**Comment by superbock** [comment]
Yes, that's true. I thought I had a check included for DBN tempo estimation (in the old code before tempo refactoring), but I can't find it right now. Anyways, #376 fixes this. Thanks for reporting!

**Comment by SebastianPoell** [comment]
Thanks for fixing 👍
