### ISSUE TITLE
Real time beat detection

### ISSUE THREAD

**Issue by lukasstevens** [CPJKU/madmom#382]
When introducing a streaming mode (now called online mode?) in #185, it was considered whether to flush more often when working with streaming data. I'd like to use madmom, specifically `DBNBeatTracker`, to detect beats and react to them in real time; however, the detected beats are only written to stdout in rather large time intervals. 

Would it be sensible to add an option to the parser such that the flushing interval can be set? If not, how would I go about implementing this myself?

**Comment by superbock** [comment]
What do you mean by rather large time intervals?

The beats should be written to STDOUT as soon as they are detected. IIRC, there were some issues with a specific numpy version which should have been solved in the meantime. Are you on the current master branch or on an older pip release?

**Comment by lukasstevens** [comment]
I pulled the master branch and tried it again. Unfortunately it does not work. My configuration is the following:
```
$ pip --version
pip 18.1 from /home/lukas/.virtualenvs/madmom/lib/python3.6/site-packages/pip (python 3.6)
```
I installed the packages from `requirements.txt`:
```
$ pip3 install -r requirements.txt 
Collecting numpy>=1.8.1 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/22/02/bae88c4aaea4256d890adbf3f7cf33e59a443f9985cf91cd08a35656676a/numpy-1.15.2-cp36-cp36m-manylinux1_x86_64.whl
Collecting scipy>=0.16 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/a8/0b/f163da98d3a01b3e0ef1cab8dd2123c34aee2bafbb1c5bffa354cc8a1730/scipy-1.1.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting cython>=0.25 (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/19/8e/32b280abb0947a96cdbb8329fb2014851a21fc1d099009f946ea8a8202c3/Cython-0.28.5-cp36-cp36m-manylinux1_x86_64.whl
Installing collected packages: numpy, scipy, cython
Successfully installed cython-0.28.5 numpy-1.15.2 scipy-1.1.0
```
Furthermore, I had to install mido:
```
$ pip install mido
Collecting mido
  Downloading https://files.pythonhosted.org/packages/20/0a/81beb587b1ae832ea6a1901dc7c6faa380e8dd154e0a862f0a9f3d2afab9/mido-1.2.9-py2.py3-none-any.whl (52kB)
    100% |████████████████████████████████| 61kB 1.4MB/s 
Installing collected packages: mido
Successfully installed mido-1.2.9
```
I get the first flush after 89 seconds.

**Comment by superbock** [comment]
Ok, the requirements are met. However, I am not sure why you copied `DBNBeatTracker`. Are you sure, it is using the newly installed `madmom` instead of any oder version installed via `pip`.

IIRC, the problem of output not being flushed occurred only for Python 3, more specifically `np.savetxt` not flushing the output immediately. https://github.com/CPJKU/madmom/commit/c4dc6414093bc6830687cb707772444c6a75661b is the change I am referring to. Can you please double check that the new code is used and `np.savetxt` is not involved any more?

**Comment by superbock** [comment]
It still sounds to me that there is another installation lurking somewhere. The question is if the currently installed functionality to write the beats is actually used or not. Can you debug a call to `DBNBeatTracker`?

Another thing to try is to use Python 2, IIRC this problem only occurred with Python 3.

**Comment by superbock** [comment]
Is there a reason to avoid installing it via `setup.py`? You can install madmom locally with `--user` or run in `develop` mode. But `setup.py` is needed to compile the extensions.

**Comment by lukasstevens** [comment]
I just installed it once with python2.7 and once with python3. With python2.7 the issue does not occur, with python3 it does.

**Comment by superbock** [comment]
That's good to hear. I have to further investigate the Python 3 issue. Can you confirm that the delay in reporting is basically the length of the audio file you're using, i.e. it flushes the results at the end after processing all frames?

**Comment by lukasstevens** [comment]
No, it flushes multiple times while reading the audio file. The first flush is after about 90 seconds, but the file is about 480 seconds long.

**Comment by superbock** [comment]
Ok, I can reproduce it with Python 3 as well. Can you try if adding a `f.flush()` after `f.write(bytes((string + '\n').encode(ENCODING)))` in [line 120 of madmom/io/__init__/py](https://github.com/CPJKU/madmom/blob/master/madmom/io/__init__.py#L120) solves the problem?

**Comment by lukasstevens** [comment]
That solves the issue!

**Comment by superbock** [comment]
Great, I'll commit a fix soon. Thanks for reporting!

**Comment by lukasstevens** [comment]
Thanks for the quick reply! Great project :)
