### ISSUE TITLE
Support loading ReplayGain tagged files

### ISSUE THREAD

**Issue by declension** [CPJKU/madmom#399]
It'd be great if the FFmpeg audio loading helpers supported [ReplayGain](https://en.wikipedia.org/wiki/ReplayGain) tags in the audiofiles.

Many people have their music tagged with this to allow volume levelling, but currently AIUI the FFmpeg `io` helpers (based around `_ffmpeg_call`) don't process these tags. Consequently it's hard to set thresholds and other parameters for feature analysis / display etc with a >12dB average volume range across files.

Luckily FFMpeg has [in-depth support for RG volume adjustment](https://ffmpeg.org/ffmpeg-all.html#volume)...

**Comment by superbock** [comment]
That's an excellent idea! I am not sure if this has a lot of impact on the NN-based methods, though.

Feel free to send a PR, I might not have time to incorporate this until next month.
