### ISSUE TITLE
'music tempo estimation' is the same as 'music classification'?

### ISSUE THREAD

**Issue by THtanghuan** [CPJKU/madmom#407]
Hello.
Recently,I do some research on music classification .I wan't to know that 'music tempo estimation' is the same as 'music classification'?

**Comment by superbock** [comment]
First of all, this is unfortunately not the right place to ask generic questions like this. Github issues should be used for issues with madmom (e.g. non-working things, errors) or questions specific to madmom but not for general questions. Try asking on the ISMIR community mailing list (https://groups.google.com/a/ismir.net/forum/#!forum/community).

Besides that, I fear I cannot really answer this questions. If you see tempo estimation as some kind of classification problem — then yes. You classify which tempo a piece has. But others may disagree.
