### ISSUE TITLE
Onset detection datasets?

### ISSUE THREAD

**Issue by bjourne** [CPJKU/madmom#412]
Sorry for asking on the issue tracker, but the mailing list seem dead. :) I'm very interested in onset detection and would like to write my own algorithms based on those found in madmom. But I can't find the datasets to train the ann models anywhere on the net. Is there any way I can get access to them?

**Comment by superbock** [comment]
Please have a loot at our ISMIR 2018 tutorial, more specifically on part 3:
https://github.com/slychief/ismir2018_tutorial/blob/master/Part_3a_Onset_Detection.ipynb
https://github.com/slychief/ismir2018_tutorial/blob/master/Part_3b_RNN_Onset_Detection.ipynb

P.S. somehow my email subscription to that forum was removed, so I did not receive any notifications. Sorry for not responding there.
