### ISSUE TITLE
Installation issue, mabe wheels-related

### ISSUE THREAD

**Issue by stefan-balke** [CPJKU/madmom#422]
### Expected behaviour

`pip install madmom==0.16.1`

should just work.

### Actual behaviour
```
>>> import madmom
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/stefan/miniconda3/envs/asr/lib/python3.6/site-packages/madmom/__init__.py", line 24, in <module>
    from . import audio, evaluation, features, io, ml, models, processors, utils
  File "/home/stefan/miniconda3/envs/asr/lib/python3.6/site-packages/madmom/audio/__init__.py", line 27, in <module>
    from . import comb_filters, filters, signal, spectrogram, stft
  File "__init__.pxd", line 918, in init madmom.audio.comb_filters
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
>>> 
```

### Fix

Install `madmom` without using binaries/wheels:

`pip install madmom --no-binary :all:`

I'm not too familiar with Pypi and the wheels and where they come from but maybe the provided wheel was build with an older `numpy` version?
Maybe my case is also special since I have to use `numpy=1.15.4` in order to work with `theano`...

### Information about installed software

Please provide some information about installed software.

Ubuntu 18.04
Miniconda on Python 3.6
```
>>> np.__version__
'1.15.4'
>>> scipy.__version__
'1.1.0'
```

**Comment by superbock** [comment]
I think it is due to an older cython version. Pypi packages of madmom come with cythonised versions of the .pyx files. Seems this is not such a good idea.

Your fix does help since it forces cython to cythonise the modules beforehand.

**Comment by stefan-balke** [comment]
Thanks!
