### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'func'. 

### ISSUE THREAD

**Issue by Irinnisar** [CPJKU/madmom#426]
### Expected behaviour

I want to execute the madmom code like in bin directory which is use argument parser.
But, there is problem in my code.

### Actual behaviour

Please paste what it does instead.

Here is my code:
```python
from madmom.processors import (IOProcessor, io_arguments)
from madmom.features.beats import (RNNBeatProcessor, DBNBeatTrackingProcessor)
from madmom.io import write_beats
from argparse import ArgumentParser

if __name__ == '__main__':
    # define parser
    p = argparse.ArgumentParser()
    # add I/O related arguments and define
    # single/batch/pickle processing mode
    madmom.processors.io_arguments(p, output_suffix='beats.txt')
    # parse arguments
    args = p.parse_args()
    # define beat tracking processor
    rnn = madmom.features.beats.RNNBeatProcessor()
    dbn = madmom.features.beats.DBNBeatTrackingProcessor(fps=100)
    out = madmom.io.write_beats
    # wrap as IOProcessor
    processor = madmom.processors.IOProcessor([rnn, dbn], out)
    # call the processor in single/batch/pickle
    # mode defined by ‘args.func‘
    args.func(processor, **vars(args))
```
But the results:

  File "C:\Users\IRINNISAR\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "F:/cobayaa/cobaargparse.py", line 102, in <module>
    args.func(processor, **vars(args))

**AttributeError: 'Namespace' object has no attribute 'func'**

### Information about installed software

Please provide some information about installed software.

python version 3.7 using spyder in anaconda navigator
madmom version 0.16.1
np version 1.15.4
scipy version  1.1.0
```

**Comment by superbock** [comment]
I updated your issue to display code correctly.

The code should work (as far as I can see), but what is suspect that the error is thrown in line 102 of `F:/cobayaa/cobaargparse.py`. It looks like you have something in your Python path which chooses this argparser(?) over the default one.

**Comment by Irinnisar** [comment]
Actually, I don't know which one the madmom code that should be run for making running led based on detection of music beats project. I've tried this following code and already found the beats.

`from madmom.features.beats import (RNNBeatProcessor, DBNBeatTrackingProcessor)
from madmom.processors import SequentialProcessor
# define beat tracking processor
rnn = RNNBeatProcessor()
dbn = DBNBeatTrackingProcessor(fps=100)     #(min_bpm=50, max_bpm=200)
tracker = SequentialProcessor([rnn, dbn])
# track the beats by calling the processor
beats = tracker('kontre.wav')`

the result is 
beats=
array([ 0.18,  0.83,  1.49,  2.19,  2.86,  3.55,  4.24,  4.93,  5.61,
        6.29,  6.98,  7.66,  8.33,  9.02,  9.7 , 10.4 , 11.08, 11.76,
       12.45, 13.12, 13.78, 14.46, 15.15, 15.83, 16.52, 17.2 , 17.88,
       18.56, 19.24, 19.94, 20.62, 21.31, 22.01, 22.69, 23.35, 24.03,
       24.72, 25.4 , 26.08, 26.78, 27.45, 28.1 , 28.78, 29.46])


but, I am confuse how to transfer the beats into Arduino and make them real time. So, I've tried the code in madmom /bin like from installation guide said:

Executable programs
The package includes executable programs in the /bin folder. These are standalone reference implementations of the algorithms contained in the package. If you just want to try/use these programs, please follow the instruction to install from a package.


Nah, I think the code is to make the detection beats become real time. (I really really don't know to make them real time (the beats will be detected as fast as the music being played)). If u have some information I am very thanks for that. :)

**Comment by superbock** [comment]
`DBNBeatTracker` is able to detect beats in real-time, simply use it as it is in `online` mode. It writes the detected beats to STDOUT as soon as the occur in the audio signal. You could then pass this information to an Arduino or process further as you like.

**Comment by Irinnisar** [comment]
I've run in spyder anaconda navigator using python 3.7 but the problem is in args.func(processor, **vars(args)) like I said before. So, is my problem in my argparse package? Thanks a lot for your response.

**Comment by superbock** [comment]
As I said before, the problem is most likely that `F:/cobayaa/cobaargparse.py` file. This is definitely not a standard Python package and should not be called. Try removing this file if you don't need it any more or better install madmom in a virtual env. This is not a madmom problem, it's a problem of your local install and thus I can't help with this unfortunately.

**Comment by Irinnisar** [comment]
Hmm it's not a python package but it's the name of my python file project.

**Comment by superbock** [comment]
Sorry, it was not clear to me that this is the file you're calling (although the error should have suggested this).

Did you try running it outside of Spyder? Unfortunately, I cannot really help with this, since I don't use Spyder and Windows. But madmom itself seems to work as you were able to detect beats in an audio file.

**Comment by Irinnisar** [comment]
Oh, ya, I'm using windows. Sorry for not tell it previously.
I've been downgrade to the python 2.7 and run the program above. I don't find the problems anymore.

The result is
bismillah.py [-h] [-v] {pickle,single,batch} ...
bismillah.py: error: too few arguments (bismillah is my file name)

Would you give me some rules how to run the program? Because I don't know the way to run it until I can see the beats found in command prompt (like the video I've seen in you tube) one by one? Thank you.

**Comment by superbock** [comment]
When run in online mode, the program (`DBNBeatTracker online`) prints the beats as they occur to STDOUT. If not, this is most likely because of some caching of your terminal (but I cannot test nor verify this).

**Comment by Irinnisar** [comment]
It should also can be run on Windows right? From terminal I got this, what should I do next?

C:\Python2.7>python progg.py single -h
usage: progg.py single [-h] [-o OUTFILE] [-j NUM_THREADS] infile

positional arguments:
  infile          input audio file

optional arguments:
  -h, --help      show this help message and exit
  -o OUTFILE      output file [default: STDOUT]
  -j NUM_THREADS  number of threads [default=4]

And then I try...

C:\Python2.7>python progg.py single -h STDOUT 4 kontre.wav
usage: progg.py single [-h] [-o OUTFILE] [-j NUM_THREADS] infile

positional arguments:
  infile          input audio file

optional arguments:
  -h, --help      show this help message and exit
  -o OUTFILE      output file [default: STDOUT]
  -j NUM_THREADS  number of threads [default=4]

**Comment by superbock** [comment]
First of all if you add `-h`, the help will be displayed and nothing else will ever happen. I really can't comment on your code, only on the stuff included in madmom. That's why I suggested to test if `DBNBeatTracker` (included in the `/bin` directory or installed somewhere during `pip install`) produces the desired output. If this works, then I suggest to use this script as an example on how should/could be used. Or use it's output to be piped to another process or to your Arduino.

And yes, it should run on Windows, but since I don't use Windows, I can't with problems related to that OS.

**Comment by Irinnisar** [comment]
Yah, I've found it.
C:\Users\IRINNISAR\Anaconda3\envs\py2\Scripts>python DBNBeatTracker single kontre.wav
0.180
0.830
1.490
2.190
2.860
3.550
4.240
4.930
5.610
6.290
6.980
7.660
8.330
9.020
9.700
10.400
11.080
11.760
12.450
13.120
13.780
etc. . .

**Comment by superbock** [comment]
Great, you can also run this program in `online` (instead of single) mode in order to process an input file or a live audio stream (requires `pyaudio`) frame by frame.

**Comment by Irinnisar** [comment]
Yeah, thank you Sir. How's the code should I call if I want to connect it to a live audio stream? I've been installed pyaudio. Is like python DBNBeatTracker single (--------) ? What should I fill in that blank?

**Comment by superbock** [comment]
Nothing :) Simply `DBNBeatTracker online`. `-v` adds some verbose output (like RNN activations and DBN state space) which might be useful for tests.

**Comment by Irinnisar** [comment]
Hmm i found problem again :)

C:\Users\IRINNISAR\Anaconda3\envs\py2\Scripts>python DBNBeatTracker online
**Could not import the PyAudio C module '_portaudio'.**
Traceback (most recent call last):
  File "DBNBeatTracker", line 111, in <module>
    main()
  File "DBNBeatTracker", line 107, in main
    args.func(processor, **vars(args))
  File "C:\Users\IRINNISAR\Anaconda3\lib\site-packages\madmom\processors.py", line 857, in process_online
    stream = Stream(**kwargs)
  File "C:\Users\IRINNISAR\Anaconda3\lib\site-packages\madmom\audio\signal.py", line 1390, in __init__
    import pyaudio
  File "C:\Users\IRINNISAR\Anaconda3\lib\site-packages\pyaudio.py", line 116, in <module>
    import _portaudio as pa
ImportError: DLL load failed: The specified module could not be found.

What should I do?

**Comment by superbock** [comment]
The error message says, that it can't find the pyaudio DLL. So this is not a madmom issue, but rather a pyaudio one. http://people.csail.mit.edu/hubert/pyaudio/ lists instructions on how to install pyaudio. Unfortunately, they do not provide wheels for Python 3.7, so you have to compile pyaudio yourself. Another option is to use Python 3.6 instead of 3.7.

HTH and good luck solving this issue.

**Comment by Irinnisar** [comment]
Dear Bock,

I'm Irin from Indonesia, an undergraduate student who working on a college project.
I have read your research entitled detection of enhanced beat tracking with context aware neural network.
I have question that I want to ask to you. Could madmom package play music while detecting beat? I mean the music sounds will be heard from the computer speaker.

Really hope you reply my email.
Thank you.
Best Regards.

**Comment by superbock** [comment]
There's no such functionality built in. But you can do this with external tools, e.g. Sonic-Visualiser. Simply load the audio file and the detected beats and play it back. If you need this for more than a couple of files, you need to code this by yourself. Librosa seems to have the desired functionality: https://librosa.github.io/librosa/generated/librosa.core.clicks.html

**Comment by Irinnisar** [comment]
Dear Bock, thank you for the information you have told in the previously.

I want to ask again, how to open the nn models as in folder madmom/models/beat_lstm_1.pkl?
Because I want to know the code inside the pkl format. When open the file I found some unidentified charachters. Is that a kind of pickle file format?

**Comment by superbock** [comment]
These are pickle files you can open with Python's own pickle mechanism. But this would have been very easy to try by yourself... There's not really code inside, only the neural network classes and the corresponding weights and biases.

**Comment by Irinnisar** [comment]
oh ya, could you give me an example about the code using LSTMlayer? Because of from the package example use feedforwardlayer not LSTMlayer.

```
import numpy as np
import madmom
from madmom.ml.nn.layers import LSTMLayer
from madmom.ml.nn.activations import tanh, sigmoid

l1_weights = np.array([[0.5, -1., -0.3 , -0.2]])
l1_bias = np.array([0.05, 0., 0.8, -0.5])
l1_recurrentweights = np.array ([0.1, 0.2, 0.3, 0.4])
l1_peepholeweights = np.array ([0.5])
l1 = LSTMLayer(l1_weights, l1_bias, l1_peepholeweights, l1_recurrentweights, activation_fn=tanh)


l2_weights = np.array([-1, 0.9, -0.2 , 0.4])
l2_bias = np.array([0.5])
l2_recurrentweights = np.array ([0.01, 0.02, 0.03, 0.04])
l2_peepholeweights = np.array ([0.5])
l2 = LSTMLayer(l2_weights, l2_bias, l2_recurrentweights, l2_peepholeweights, activation_fn=sigmoid)

nn = madmom.ml.nn.NeuralNetwork([l1, l2])
nn.dump('neural_net.pkl')

```
and i get error

```
l1 = LSTMLayer(l1_weights, l1_bias, l1_peepholeweights, l1_recurrentweights, activation_fn=tanh)

  File "madmom/ml/nn/layers.py", line 355, in madmom.ml.nn.layers.LSTMLayer.__init__
    init = np.zeros(self.cell.bias.size, dtype=NN_DTYPE)

AttributeError: 'numpy.ndarray' object has no attribute 'bias'
```

**Comment by Irinnisar** [comment]
And, again, how about the training and testing data? How many iterations that is needed?

**Comment by superbock** [comment]
The docstring of `LSTMLayer` clearly states that cell must be of type `Cell` and must be passed to `LSTMLayer` during initialisation. Your example is not supposed to work, because you're not following the required initialisation signature, i.e. `LSTMLayer(input_gate, forget_gate, cell, output_gate)`.

But besides that, I am not sure if madmom is the right tool for what you're trying to accomplish. Formerly you were trying to track the beats and madmom can do this for you.

Now you're asking about how to use LSTMLayer, and how to train and test a neural network. madmom is not for training networks, you have to do this with another tool. madmom is a signal processing library and contains a collection of reference implementations of papers I and some colleagues wrote, and those usually contain neural networks (NN). That's the reason madmom comes with NN-related code. For an example of usage, please refer to the paper.

Please don't get me wrong, but maybe you should get yourself a bit more familiar with Python and neural networks before trying to use madmom's very specific NN-code to accomplish something you did not even explain beforehand...

HTH

**Comment by Irinnisar** [comment]
Oh ya I get it. do you have a sample LSTM code that is used to detect beats? Or some code references about it.
Thank you.

**Comment by Irinnisar** [comment]
Could you please give some codes of your ONLINE REAL-TIME ONSET DETECTION WITH RECURRENT NEURAL NETWORKS paper, Sir? I'm really need, but It doesnt matter if the codes couldn't be published. Or could I have your email address? Maybe I can continue by messaging via email. My email is choirinnisar@gmail.com. Thank you.

**Comment by superbock** [comment]
Everything is online and contained in this repository :)

For online real-time onset detection, please see the reference implementation `OnsetDetectorLL` in the bin directory, for (B)LSTM beat tracking `DBNBeatTracker`.

**Comment by Irinnisar** [comment]
Hallo sir, I'm sorry if I want to ask again.
My question is, when I run `python DBNBeatTracker online` why the beat is still detected when I stop the playing music from my microphone? Thank you

**Comment by superbock** [comment]
Because RNNs have recurrent connections which take previous time steps into consideration. Also the DBN tries to detect beats even if there's only a very low activation. If you want to stop immediately, you need to monitor the activations and set a threshold by yourself.

HTH

**Comment by Irinnisar** [comment]
Sir, I want to ask again.
Does the binnary classifier that you use in the making of network output layer consist of one output unit value? And, do you use the sigmoid activation function with the crossentrophy binnary losses function?

Then, the input for each frame of the target sequence consists of (120, N), can I illustrate it like this:
If at annotation there are 0.2  0.5  1  1.5 (we ignore downbeat), does that mean beats are occur at frames 20, 50, 100, and 150? So, in each frame has 1 as the target value? 1 for beats, and 0 for no beats.

**Comment by superbock** [comment]
Yes, that's correct.

**Comment by Irinnisar** [comment]
Thanks a lot. And then, how to visualize or plot the hidden feature after pass each hidden layer? And how to plot the beat from the final layer (or from beat activation function)? Is that use keras visualizing layer representations?

**Comment by superbock** [comment]
I am sorry, but I can't help with this.
