### ISSUE TITLE
anaconda2/lib/python2.7/site-packages/madmom/ml/nn/layers.so: undefined symbol: PyFPE_jbuf

### ISSUE THREAD

**Issue by fzhafran** [CPJKU/madmom#432]
ImportError: /home/fzhafran/anaconda2/lib/python2.7/site-packages/madmom/ml/nn/layers.so: undefined symbol: PyFPE_jbuf

When try to import madmom, i got the error. How to fix the error?

Anaconda2 in linux x86, ubuntu 16.04
numpy 1.16.13
scipy 1.2.1
cython 0.29.7
mido 1.2.9

**Comment by superbock** [comment]
Maybe you have two versions of numpy installed. If yes, please uninstall the non-anaconda one (assuming you want to use anaconda). Please see https://stackoverflow.com/questions/36190757/numpy-undefined-symbol-pyfpe-jbuf for details.

**Comment by superbock** [comment]
Closing this issue, feel free to reopen if this error still persists.
