### ISSUE TITLE
CNNKeyRecognitionProcessor's answers are not accurate

### ISSUE THREAD

**Issue by VtlNmnk** [CPJKU/madmom#433]
Hello! I'm trying to determine the general key of the short wav files: minor or major. So, I downloaded short wav files with the keys specified in the name from here https://github.com/orchidas/Chord-Recognition/tree/master/test_chords
and I try to identify the wav file major or minor keys with this code:
[test4.py.txt](https://github.com/CPJKU/madmom/files/3236267/test4.py.txt)

    from madmom.features.key import CNNKeyRecognitionProcessor, key_prediction_to_label
    import os

    proc = CNNKeyRecognitionProcessor()
    folder = 'test_chords'
    listing = os.listdir(folder)
    correct_answer_num = 0
    for file in listing: 
        print("###################################################################")
        print(os.path.join(folder, file))

        prediction = proc(os.path.join(folder, file))

        answer = key_prediction_to_label(prediction)
        print(answer)
        if ("minor" in os.path.join(folder, file) and "minor" in answer)\
                or ("major" in os.path.join(folder, file) and "major" in answer):
            print("Correct answer!!!")
            correct_answer_num += 1

    print("correct answers =", correct_answer_num)
    print("total wav files processed = ", len(listing))
    print("accuracy` =", correct_answer_num/len(listing)*100, "%")

Current average accuracy:
[test4_response.txt](https://github.com/CPJKU/madmom/files/3236248/test4_response.txt)
correct answers = 13
total wav files processed =  24
accuracy = 54.166666666666664 %

### Information about installed software
madmom.__version__
'0.16.1'
np.__version__
'1.16.4'
scipy.__version__
'1.3.0'

How to use CNNKeyRecognitionProcessor in right way?
Or did I take the wav files with wrong keys specified in the names?

**Comment by fdlm** [comment]
Hi, sorry for the late answer. The results you show are not very surprising. First, if you listen to your test data, you will hear that all the recorded "major" chords are actually recordings of single pitches and not triads (you can also look at the spectrogram). Second, the model was not trained to classify single piano chords as "key" (in fact, the recordings could be in any key that contains the played chord). Third, following from 1) and 2), if you look at the results, for the "minor" recordings, the model is correct most of the time, and when it does not get the correct one, it is usually a related key (parallel minor, etc...). So I don't think the model behaves incorrectly here.
