### ISSUE TITLE
Log filtered spectrogram height

### ISSUE THREAD

**Issue by iterspatial** [CPJKU/madmom#434]
I was under the impression that only changing the frame size for a LogarithmicFilteredSpectrogram wouldn't change the height of the spectrogram, but it does. Also with a lower frame size, low frequencies aren't being shown. Anyone know why this happens? 

```
frame_size = 8392 
fsig_proc = FramedSignalProcessor(frame_size=frame_size, fps=120, hop_size=frame_size // 2, origin='future')
spec_proc = LogarithmicFilteredSpectrogramProcessor(LogarithmicFilterbank, num_bands=32, fmin=1, fmax=8000) 
processor = SequentialProcessor([fsig_proc, spec_proc])
comp_spec = processor(Signal(np.array(y), sample_rate=fs)).T
plt.imshow(comp_spec[:, 3500:4500], cmap='magma', interpolation='nearest', aspect='auto', origin='lower')
plt.show()

frame_size = 2048
fsig_proc = FramedSignalProcessor(frame_size=frame_size, fps=120, hop_size=frame_size // 2, origin='future')
spec_proc = LogarithmicFilteredSpectrogramProcessor(LogarithmicFilterbank, num_bands=32, fmin=1, fmax=8000) 
processor = SequentialProcessor([fsig_proc, spec_proc])
comp_spec = processor(Signal(np.array(y), sample_rate=fs)).T
plt.imshow(comp_spec[:, 3500:4500], cmap='magma', interpolation='nearest', aspect='auto', origin='lower')
plt.show()
```
Top graph is a spectrogram with frame size 8392, bottom has frame size 2048.
![Screenshot from 2019-06-16 17-28-07](https://user-images.githubusercontent.com/47485510/59570338-49bc9f00-905c-11e9-83ee-e63a1944edfc.png)
Thank you

**Comment by superbock** [comment]
If the number of frequency bins is what you're referring to with height, the explanation is quite simple. With smaller frames sizes, the corresponding FFT size is smaller, and so is the frequency resolution. If the freq. resolution of the STFT is lower than the idealised/computed/wanted frequency spacing, this would lead to "duplicate" bins, i.e. the different frequency bands would be mapped to the same STFT bin.

Per default, all filtered Spectrogram classes remove these duplicate bins, which leads to different number of bands. If this is not wanted, you can simply set `unique_filters` to `False`.

**Comment by iterspatial** [comment]
Thanks for your response. Is there any other way to increase the representation of lower frequencies apart from increasing the fft_size? I'm mainly worried about the decrease in time resolution.

**Comment by superbock** [comment]
I fear, there's no other way. Where should this information come from, if it's not contained in the STFT. And time resolution depends solely on the used `hop_size` or `fps` setting.

**Comment by iterspatial** [comment]
If my understanding of spectrograms is correct, I thought that increasing the fft_size leads to higher frequency resolution but lower time resolution.

**Comment by superbock** [comment]
No, time resolution depends only on the hop size between adjacent.

Longer FFT sizes only affect time resolution if the frame size is coupled to the FFT size and you use e.g. a constant overlap between frames.

**Comment by superbock** [comment]
Closing this issue, feel free to reopen if things are still not clear.
