### ISSUE TITLE
pip install failed python 2.7

### ISSUE THREAD

**Issue by tylderen** [CPJKU/madmom#435]
ERROR: Complete output from command python setup.py egg_info:
21:30:38     ERROR: Traceback (most recent call last):
21:30:38       File "<string>", line 1, in <module>
21:30:38       File "/tmp/pip-install-vk2nF5/madmom/setup.py", line 12, in <module>
21:30:38         from Cython.Build import cythonize, build_ext
21:30:38     ImportError: cannot import name build_ext

Can anyone tell me why? Thanks!

**Comment by superbock** [comment]
You need a more recent Cython.

**Comment by tylderen** [comment]
> You need a more recent Cython.

Thank you for your reply.  Which version can be ok? How about 0.29.10 of Cython?

**Comment by tylderen** [comment]
> > You need a more recent Cython.
> 
> Thank you for your reply. Which version can be ok? How about 0.29.10 of Cython?

I tried the newest version of Cython. That's ok. Thanks again !
