### ISSUE TITLE
How many CPUs and Memories are proper for running this process? Is there best practice? 

### ISSUE THREAD

**Issue by tylderen** [CPJKU/madmom#436]
I found it  was too slow when I running it in docker with 4 CPUs and 4G memories. Thanks!

**Comment by superbock** [comment]
Being (subjectively) too slow is not an issue per se. Can you elaborate what you expected or describe any real problem you encountered?

**Comment by superbock** [comment]
Closing this issue, feel free to reopen and add more information.
