### ISSUE TITLE
How to specify audio device for DBNBeatTracker in online mode

### ISSUE THREAD

**Issue by Beefy-Swain** [CPJKU/madmom#459]
DBNBeatTracker really loves to default to using my microphone.

I see that the `Stream` class includes a kwarg to specify the input device, but I see no way in the DBNBeatTracker to do so.

https://madmom.readthedocs.io/en/latest/modules/audio/signal.html?highlight=Stream#madmom.audio.signal.Stream

**Comment by Beefy-Swain** [comment]
I think I found the secret sauce: https://github.com/CPJKU/madmom/blob/805c08e69b4390ce763c098474b2f96fab47bf60/madmom/processors.py#L878

I am trying to figure out how to add `stream_input_device` to the kwargs there, but have not been successful thus far. The was this library is structured is very different from what I am accustomed to.

**Comment by Beefy-Swain** [comment]
Found more secret sauce: https://github.com/CPJKU/madmom/blob/3aa9837112f32d232a1b257af59ad8891c3931f7/madmom/processors.py#L1002

So I just need to add the argument to the end of the call to `args.func`

**Comment by Beefy-Swain** [comment]
`args.func(processor, stream_input_device=7, **vars(args))` does not appear to work, unsure why.

**Comment by Beefy-Swain** [comment]
Digging into the `Stream` implementation of both madmom and of pyaudio, it seems like they default to the default input device if unspecified or `None`. What I do not know is how that default device is selected.

Furthermore, setting that default device at the OS level isn't a very portable or sustainable solution for what I need, so it's not a good solution.

**Comment by Beefy-Swain** [comment]
So I installed from source rather than from PyPI, and am now seeing a different error.

Adding `args.stream_input_device = 7` to the `DBNBeatTRracker.py` module results in the following error:

```Expression 'parameters->channelCount <= maxChans' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1514
Expression 'ValidateParameters( inputParameters, hostApi, StreamDirection_In )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2818
Traceback (most recent call last):
  File "./DBNBeatTracker2.py", line 123, in <module>
    main()
  File "./DBNBeatTracker2.py", line 119, in main
    args.func(processor, **vars(args))
  File "/home/bkirkbride/Projects/ambitious_audio/madmom/madmom/processors.py", line 878, in process_online
    stream = Stream(**kwargs)
  File "/home/bkirkbride/Projects/ambitious_audio/madmom/madmom/audio/signal.py", line 1602, in __init__
    start=True,
  File "/home/bkirkbride/Projects/ambitious_audio/venv/lib/python3.7/site-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/home/bkirkbride/Projects/ambitious_audio/venv/lib/python3.7/site-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9998] Invalid number of channels
```

**Comment by Beefy-Swain** [comment]
It's possible I fundamentally misunderstand how this feature is supposed to work. I have been proceeding under the assumption that I can specify the device that I am using to output the audio, and have it monitor that. Is that incorrect? Will this only work for "input" (if that's a thing??) type devices?

**Comment by Beefy-Swain** [comment]
>stream_input_device : int, optional
>PyAudio device index of the desired input device.

That does seem to imply that this only works for input devices.

**Comment by superbock** [comment]
The error you pasted above is maybe a bit misleading, but it is clear that this error is related to pyaudio and not madmom.

I am not really into pyaudio, but I assume that only input devices can be used as input — and not output devices (I get the same error if I specify an output device as input). Can you post the list of available devices (`DBNBeatTracker onlie --list`), one of them should be an input device if your hardware supports monitoring.

**Comment by Beefy-Swain** [comment]
```0: HDA NVidia: HDMI 0 (hw:0,3)
1: HDA NVidia: HDMI 1 (hw:0,7)
2: HDA NVidia: HDMI 2 (hw:0,8)
3: HDA NVidia: HDMI 3 (hw:0,9)
4: HD-Audio Generic: ALC1220 Analog (hw:1,0)
5: HD-Audio Generic: ALC1220 Digital (hw:1,1)
6: HD-Audio Generic: ALC1220 Alt Analog (hw:1,2)
7: DAC-X6: USB Audio #1 (hw:2,1)
8: hdmi
9: pulse
10: default
```

Device 7 is what I wanted to use, but it is an output device.

I was able to specify the output monitor using PulseAudio, but I don't know if/which device that corresponds to above.

I think the solution here is to use something like JACK to route the applications through an input bus in software and feed that to the PyAudio.

**Comment by superbock** [comment]
The IDs listed with `--list` are those which can be specified with `--device` (which is what is passed through `Stream`).

I don't know about Linux sound infrastructure, but in Mac OS you can define routes in software which can then be used as input and output simultaneously.
