### ISSUE TITLE
Code missing for ISMIR 2019 article?

### ISSUE THREAD

**Issue by matangover** [CPJKU/madmom#470]
Hi, thanks for this wonderful library! Where can I find the code for the ISMIR 2019 article: "Multi-Task Learning of Tempo and Beat: Learning One to Improve the Other"? The article links to this repo but I can't find the corresponding code or trained models.

**Comment by matangover** [comment]
Related? https://github.com/CPJKU/madmom_models/issues/16

**Comment by snownstone** [comment]
I guess what you want is  [here](https://github.com/superbock/ISMIR2019)?

**Comment by matangover** [comment]
Unfortunately not, that repo doesn't contain the code.

**Comment by superbock** [comment]
If you are referring to the inference code, I will add it together with the models soon. I left academia a while ago so I have to do this in my free time.

The code to train a model was never included and there are no plans to release it. But the description in the paper should contain all details to reproduce this work.

**Comment by matangover** [comment]
Thank you. I'm looking mainly for the inference code and trained models.
