### ISSUE TITLE
Code to calculate beat.

### ISSUE THREAD

**Issue by Kunal2341** [CPJKU/madmom#473]
I need to get a code that will calculate the general beat of a song. Overall tempo would be nice too. I have an mp3/wav file and like a list with the all-time point where the beat is located. 

I see you have this 
https://github.com/CPJKU/madmom/blob/master/madmom/features/beats.py
But I don't know how to use it in python

Thanks

```

**Comment by superbock** [comment]
Please have a look at the scripts provided in the [`bin` directory](https://github.com/CPJKU/madmom/tree/master/bin), more specifically [`DBNBeatTracker`](https://github.com/CPJKU/madmom/blob/master/bin/DBNBeatTracker), [`DBNDownBeatTracker`](https://github.com/CPJKU/madmom/blob/master/bin/DBNDownBeatTracker) and [`TempoDetector`](https://github.com/CPJKU/madmom/blob/master/bin/TempoDetector).

**Comment by Kunal2341** [comment]
I am quite new to coding, but how do I implement these files. If I download the following file and save it locally on my hard drive. I run `python TempoDetector.py` (*named file TempoDetector*). If there is another way to set it up, please let me know.

I understand that there are multiple different arguments that must be defined but I am not familiar how to do that. With `python TempoDetector.py -h` I can get the possible arguments but how do I call the single basic 
`in_processor = RNNBeatProcessor(**vars(args))`.  The other files have the same problem.

**Comment by superbock** [comment]
Please have a look at the docs: https://madmom.readthedocs.io/en/latest/
There's a dedicated section about installation. Then run the scripts with `-h` to get a help message describing the usage. The scripts do not have a `.py` extension, so you can simply determine the tempo of a file bu running `TempoDetector single file.mp3`

**Comment by Kunal2341** [comment]
Is there any way to run this in a python IDE.

**Comment by superbock** [comment]
I can't really answer this question, but generally speking: yes, but it depends on your IDE.
I'm closing this issue, since this is not an issue with madmom.
