### ISSUE TITLE
load_ffmpeg_file only loads files from current directory (library)

### ISSUE THREAD

**Issue by batson-j** [CPJKU/madmom#475]
### Expected behaviour

`load_ffmpeg_file` from `madmom.io.audio` can take in a file from any directory/path.

### Actual behaviour

```
from madmom.io.audio import load_ffmpeg_file

load_ffmpeg_file(r'C:\sample.wav')
```
returns the error `TypeError: not all arguments converted during string formatting`

Only filenames located in the calling files' path will correctly load.

```
from madmom.io.audio import load_ffmpeg_file

load_ffmpeg_file(r'sample.wav')
```

will work if `sample.wav` is in the .py file's directory.

**Comment by superbock** [comment]
I'm sorry, but I don't have windows to test this, but I am quite confident that it should work as indended — at least it works on my machine:
```
In [2]: from madmom.io.audio import load_ffmpeg_file
In [3]: load_ffmpeg_file('/Users/sb/src/madmom/tests/data/audio/sample.wav')
Out[3]:  (array([-2494, -2510, -2484, ...,   520,   655,   639], dtype=int16), 44100)
In [4]: load_ffmpeg_file('src/madmom/tests/data/audio/sample.wav')
Out[4]: (array([-2494, -2510, -2484, ...,   520,   655,   639], dtype=int16), 44100)
```
Can you please run any of the provided programs (e.g. `SuperFlux single C:\sample.wav`) to see if the same error is raised.

**Comment by batson-j** [comment]
No issues finding the file with `SuperFlux single D:\Music\test.wav'.

I also tested `madmom.io.audio.load_audio_file` and `madmom.io.audio.load_wave_file`. Both of these worked as expected and can locate files in different paths.

**Comment by superbock** [comment]
Since loading `.wav` files with the two other method works, it seems to be a problem related to `load_ffmpeg_file`. But it also seems to be related to Windows, since it works on Linux/MacOS. As indicated previously, I don't have any windows systems so I cant really help with this problem — besides the suggestion using `load_audio_file`.

**Comment by superbock** [comment]
Have you been able to solve this problem? I'm closing this issue, but feel free to re-open it if this problem still persists.
