### ISSUE TITLE
My script extracting downbeats 4-5x slower than /bin/DBNDownBeatTracker

### ISSUE THREAD

**Issue by carrus2049** [CPJKU/madmom#476]
Hi there!

With this track (44100*2, length of 5:22), using DBNDownBeatTracker takes around 18 seconds. Though using interfaces as below takes up to 70-80 seconds. Is there something missing or wrong with my script? Thanks!

### Steps needed to reproduce the behaviour

```python
import madmom.features.downbeats as dbt
from madmom.audio.signal import SignalProcessor

afp = '1_2A625C32C21F1FC15669DC793B89B850.mp3'
proc = SignalProcessor(sample_rate=22050, num_channels=1)
sig = proc(afp)
act = dbt.RNNDownBeatProcessor()(sig)
proc = dbt.DBNDownBeatTrackingProcessor(beats_per_bar=4, fps=100, transition_lambda=250)
dbeats = proc(act)

```

### Information about installed software

Please provide some information about installed software.
madmom==0.16.1
numpy==1.20.3
scipy==1.6.3

**Comment by superbock** [comment]
There's nothing really wrong with it per se, try passing `num_threads=4` to RNNDownBeatProcessor to see if you get the desired speedup.

**Comment by carrus2049** [comment]
> There's nothing really wrong with it per se, try passing `num_threads=4` to RNNDownBeatProcessor to see if you get the desired speedup.

Works like a charm. Thank you alot sir!
