### ISSUE TITLE
I want to generate MIDI file using madmom.features.notes

### ISSUE THREAD

**Issue by mohkoma** [CPJKU/madmom#477]
### Expected behaviour

I would like to detect notes from `madmom.features.notes` and then generate Midi file `madmom.io.midi` using the detected data.
Is there a way to convert `madmom.features.notes` arrays to be accepted by `MIDIFile.from_notes`?

### Actual behaviour

the `MIDIFile.from_notes` accept specific array with ‘onset time’, ‘pitch’, ‘duration’, ‘velocity’, ‘channel’.  and I can't find any way to generate this array.

Thank you in advance!

**Comment by superbock** [comment]
You can either use [`madmom.io.write_midi`](https://github.com/CPJKU/madmom/blob/805c08e69b4390ce763c098474b2f96fab47bf60/madmom/io/midi.py#L582) directly or use the  [`expand_notes`](https://github.com/CPJKU/madmom/blob/805c08e69b4390ce763c098474b2f96fab47bf60/madmom/utils/__init__.py#L463) helper function to add the missing values (velocity and duration) so it can be used by `MIDIFile.from_notes`
