### ISSUE TITLE
Window function in FramedSignalProcessor?

### ISSUE THREAD

**Issue by shreyanc** [CPJKU/madmom#483]
I can't seem to find a way to specify a windowing function in madmom. Is this a deliberate choice? (As a contrast, librosa allows this).

**Comment by superbock** [comment]
[`madmom.audio.stft.stft()`](https://github.com/CPJKU/madmom/blob/master/madmom/audio/stft.py#L49) has a `window` argument, which takes a window array.
[`madmom.audio.stft.ShortTimeFourierTransform`](https://github.com/CPJKU/madmom/blob/master/madmom/audio/stft.py#L202) additionally takes a callable function (e.g. `np.hamming`) for the same argument.

You can pass this argument to any class higher in the hierarchy (e.g. all sorts of spectrogram classes).

**Comment by shreyanc** [comment]
That clears it up. Thanks a lot!
