### ISSUE TITLE
Documentation/Examples for online mode/real-time processing

### ISSUE THREAD

**Issue by clbrec** [CPJKU/madmom#484]
The examples over at https://github.com/CPJKU/madmom_tutorials seem quite outdated. Would love to have a simple example on how to setup madmom for real-time processing, especially when reading from a stream.

cheers :)

**Comment by superbock** [comment]
I'm closing this since I think the linked thread has plenty of information. Please feel free re-opening this issue if you end up at a point you can't solve.
