### ISSUE TITLE
Input Device on DBNBeatTracker online mode

### ISSUE THREAD

**Issue by darkzbaron** [CPJKU/madmom#487]
### Expected behaviour

I would have expected Madmom to use the default input device 

### Actual behaviour

No information on actual input device used and nothing happen

### Steps needed to reproduce the behaviour

```
"madmom\bin\DBNBeatTracker" online

```

### Information about installed software

Python 37 

`
madmom          0.16.1
numpy           1.20.2
PyAudio         0.2.11
```

**Comment by darkzbaron** [comment]
Hi thanks so much for the rep. I was using an old bin file for DBNBeatTracker which caused an issue while using the latest madmom package.

It looks like you remove the ability to select the recording pyaudio device! It's a shame now I have to modify the source.

Also, any idea what would be the most appropriate algorith to animate a light to music? I am using the DBNBeatTracker but there are "not enough" beat events to my tast, I tried to increase the gain but not sure that's the right approach.

Thanks so much for the great work anyway

**Comment by superbock** [comment]
Regarding the ability to select the audio source: this should still be there (see the `--list` option of all online capable scripts to list all devices selectable with `--device`).

You might want to set `--min_bpm` to a higher value, this should force the DBN to chose a higher tempo, most likely double of the correct tempo, but please make sure to increase `--max_bpm` accordingly.

If this does not work, you could try using `OnsetDetectorLL`, but this gives all onsets of an audio, which might not be very periodic and thus less suited to control lights.

**Comment by darkzbaron** [comment]
HI there, thanks so much for your help! I am making progress using DBNBeatTracker,. I am looking to add another dimension to my script, namely the intensity of the beat, can I get that from your source or does the DBN only returns confidence level/probability?

**Comment by superbock** [comment]
The DBN returns only the positions of the beats, but you can of course re-evaluate the output of the RNN. But maybe a simple thresholding of the RNN activation is enough for your apllication.

**Comment by CodingGhost** [comment]
@superbock Hi, Im also having a similiar usecase. How can I get the RNN activation value to perform threshholding on it? and also, would the OnsetDetection be a good way of getting Beats that are not evenly spaced? For example in a buildup where tempo is increasing? How can I use the Onset detection instead of the Beat detection?

**Comment by superbock** [comment]
Just remove the last DBN part and you get the beat activations, i.e. the output of the RNN.

Not sure why you want the onset activations for beat tracking purposes, the neural networks trained to detect beats are (most likely) what you are looking for.

Of course you can replace the beat NN models with those trained for onsets, just give it a try, but I expect worse results.

**Comment by CodingGhost** [comment]
thanks for the quick reply!
my goal is that the beat detection pauses on musical breaks, for example if the beat has been going steady for some time and then there coems a break and a melody, I want to pause / dont trigger a callback, and then continue once the beat continues.

Do you have a better idea of how to accomplish that? I have no experience with sound engineering and am just trying some things.
could you elaborate what exactly you mean by "just remove the last DBN part" ? I looked into beats.py and did if np.mean(activations) < 0.2: and that seems to have something todo with it I guess? but I dont know if taking the mean is even anything meaningful..

**Comment by superbock** [comment]
If there's a pause in the music, I'd expect the output of the beat NN to have very low values. I once experimented with resetting the DBN if the beat activations were below a certain threshold, but didn't finish it. You can treat the output as some sort of probability function and thus a simple threshold might be good enough to discover breaks.

What I meant with "just remove the last DBN part" is that e.g. DBNBeatTracker works as a atwo-stage approach:
1. obtain a beat activation function (output is a likelihood that a beat is present at that time step; output has a fixed sample rate, i.e. 100 frames per second)
2. determine where the beats are located in this activation function.
To obtain the RNN beat activations, use only the first part.

**Comment by CodingGhost** [comment]
Ok, could you point me in a direction on what code I have to modify? Or do I even have to modify code? Is there a way to do this in my own script?
 
Currently Im doing it like that:

`

in_processor = RNNBeatProcessor(**kwargs)
beat_processor = DBNBeatTrackingProcessor(**kwargs)
out_processor = [beat_processor, beat_callback]
processor = IOProcessor(in_processor, out_processor)
process_online(processor, **kwargs)

`



Did I understand correctly that I can get the activation value per frame from in_processor?
and I guess I still want to use the DBNBeatTrackingProcessor, but only if the activations exceed a threshhold?
I found that in process_online there is a "activations" array with one value, that seems to be the current activation value of a single frame? but what should I do then? just return prematurely if the threshhold is not exceeded?
Im just a bit lost as to what exactly I need to do code wise to accomplish this.
