### ISSUE TITLE
Incompatible with Python 3.10 because MutableSequence was moved to collections.abc

### ISSUE THREAD

**Issue by johentsch** [CPJKU/madmom#502]
### Expected behaviour

`import madmom` would be necessary to work in order to use this library.

### Actual behaviour

Fails with
```ImportError: cannot import name 'MutableSequence' from 'collections' (..../python3.10/collections/__init__.py)```

### Steps needed to reproduce the behaviour

Import madmom under python 3.10

### Suggested solution

Import [MutableSequences](https://docs.python.org/3/library/collections.abc.html#collections.abc.MutableSequence) from `collections.abc`

**Comment by superbock** [comment]
This was fixed in https://github.com/CPJKU/madmom/commit/45e9e7b756fa66cfbe3b1f96e142ee5ad6011ec8 already, will be included in v0.17 (to be released soon). So installing from source instead of using pip should solve the problem immediately.

**Comment by idkman2021** [comment]
will 0.17 be released

**Comment by idkman2021** [comment]
> This was fixed in [45e9e7b](https://github.com/CPJKU/madmom/commit/45e9e7b756fa66cfbe3b1f96e142ee5ad6011ec8) already, will be included in v0.17 (to be released soon). So installing from source instead of using pip should solve the problem immediately.

when i try to install from source as it says i pasted "git clone --recursive https://github.com/CPJKU/madmom.git" and it said git command not found what do i do

**Comment by idkman2021** [comment]
i pasted it into cmd btw wher epython works

**Comment by frederikbrammer** [comment]
You need to install git first, otherwise it won't work.

**Comment by stunlocked1** [comment]
> You need to install git first, otherwise it won't work.

yeah thanks it didnt work when i installed git but i installed vscode and in its terminal it works

**Comment by danigb** [comment]
> This was fixed in https://github.com/CPJKU/madmom/commit/45e9e7b756fa66cfbe3b1f96e142ee5ad6011ec8 already, will be included in v0.17
@superbock what is preventing this fix to be published?

**Comment by superbock** [comment]
The CI pipelines need to be updated. Most likely we should move to Github actions, PRs welcome ;)

**Comment by davies-w** [comment]
This is still an issue, over a year later?

**Comment by f0k** [comment]
> This is still an issue, over a year later?

Well, moving to Github actions will probably take 2-3 hours of fiddling if you haven't done that before, I can sympathize with @superbock.

If you don't have git available for some reason, you can also do:
`pip install --upgrade https://github.com/CPJKU/madmom/archive/master.zip`

Or, to install a particular commit, do:
`pip install --force-reinstall --no-deps https://github.com/CPJKU/madmom/archive/45e9e7b756fa66cfbe3b1f96e142ee5ad6011ec8.zip`
