### ISSUE TITLE
madmom.features.beats TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by idkman2021** [CPJKU/madmom#512]
### Expected behaviour

No error

### Actual behaviour
```
    beats= madmom.features.beats(audio, samplerate)
TypeError: 'module' object is not callable
```
also when I omit "samplerate" it says missing argument samplerate so clearly it isn't failing to call the module
### Steps needed to reproduce the behaviour

```python
import madmom
import numpy as np
import scipy
beats= madmom.features.beats([[0.1, 0.5, 0.4, 0.8, 0.2],[0.2, 0.3, -0.4, 0.1, -0.2]], 44100)
```

### Information about installed software

Please provide some information about installed software. windows 11

```python
import madmom
import numpy as np
import scipy

madmom.0.16.1
np.1.21.5
scipy.1.9.1
```

**Comment by superbock** [comment]
As the error says, the module is not callable. You're trying to call this module, whereas you have to use any of its classes instead. Please have a look at the provided docs: https://madmom.readthedocs.io/en/v0.16.1/modules/features/beats.html
