### ISSUE TITLE
error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_type'; did you mean 'curexc_type'?  (etc)

### ISSUE THREAD

**Issue by enn-nafnlaus** [CPJKU/madmom#520]
### Expected behaviour

Compiles.

### Actual behaviour

Does not compile.

> madmom/ml/nn/layers.c:17142:25: warning: '_PyUnicode_get_wstr_length' is deprecated [-Wdeprecated-declarations]
>       17142 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
>             |                         ^
>       In file included from /usr/include/python3.10/unicodeobject.h:1046,
>                        from /usr/include/python3.10/Python.h:83,
>                        from madmom/ml/nn/layers.c:15:
>       /usr/include/python3.10/cpython/unicodeobject.h:446:26: note: declared here
>         446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
>             |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
>       madmom/ml/nn/layers.c: In function '__Pyx_PyCFunction_FastCall':
>       madmom/ml/nn/layers.c:17426:13: error: too many arguments to function '(PyObject * (*)(PyObject *, PyObject * const*, Py_ssize_t))meth'
>       17426 |     return (*((__Pyx_PyCFunctionFast)meth)) (self, args, nargs, NULL);
>             |            ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>       madmom/ml/nn/layers.c: In function '__Pyx__ExceptionSave':
>       madmom/ml/nn/layers.c:18807:21: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_type'; did you mean 'curexc_type'?
>       18807 |     *type = tstate->exc_type;
>             |                     ^~~~~~~~
>             |                     curexc_type
>       madmom/ml/nn/layers.c:18808:22: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_value'; did you mean 'curexc_value'?
>       18808 |     *value = tstate->exc_value;
>             |                      ^~~~~~~~~
>             |                      curexc_value
>       madmom/ml/nn/layers.c:18809:19: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
>       18809 |     *tb = tstate->exc_traceback;
>             |                   ^~~~~~~~~~~~~
>             |                   curexc_traceback
>       madmom/ml/nn/layers.c: In function '__Pyx__ExceptionReset':
>       madmom/ml/nn/layers.c:18816:24: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_type'; did you mean 'curexc_type'?
>       18816 |     tmp_type = tstate->exc_type;
>             |                        ^~~~~~~~
>             |                        curexc_type
>       madmom/ml/nn/layers.c:18817:25: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_value'; did you mean 'curexc_value'?
>       18817 |     tmp_value = tstate->exc_value;
>             |                         ^~~~~~~~~
>             |                         curexc_value
>       madmom/ml/nn/layers.c:18818:22: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
>       18818 |     tmp_tb = tstate->exc_traceback;
>             |                      ^~~~~~~~~~~~~
>             |                      curexc_traceback
>       madmom/ml/nn/layers.c:18819:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_type'; did you mean 'curexc_type'?
>       18819 |     tstate->exc_type = type;
>             |             ^~~~~~~~
>             |             curexc_type
>       madmom/ml/nn/layers.c:18820:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_value'; did you mean 'curexc_value'?
>       18820 |     tstate->exc_value = value;
>             |             ^~~~~~~~~
>             |             curexc_value
>       madmom/ml/nn/layers.c:18821:13: error: 'PyThreadState' {aka 'struct _ts'} has no member named 'exc_traceback'; did you mean 'curexc_traceback'?
>       18821 |     tstate->exc_traceback = tb;
>             |             ^~~~~~~~~~~~~
>             |             curexc_traceback

.. etc.

### Steps needed to reproduce the behaviour

madmom pulled in as part of installing mixingbear:

> pip install mixingbear   
> Defaulting to user installation because normal site-packages is not writeable
> Collecting mixingbear
>   Using cached mixingbear-0.0.1-py3-none-any.whl
> Requirement already satisfied: pydub<0.20.1,>=0.20.0 in ./.local/lib/python3.10/site-packages (from mixingbear) (0.20.0)
> Collecting audioowl
>   Using cached audioowl-0.0.14-py3-none-any.whl
> Collecting madmom<0.15.2,>=0.15.1
>   Using cached madmom-0.15.1.tar.gz (15.7 MB)
>   Preparing metadata (setup.py) ... done
> Requirement already satisfied: scipy in /usr/lib64/python3.10/site-packages (from audioowl->mixingbear) (1.8.1)
> Collecting librosa<0.5.2,>=0.5.1
>   Using cached librosa-0.5.1-py3-none-any.whl
> Requirement already satisfied: numpy in ./.local/lib/python3.10/site-packages (from audioowl->mixingbear) (1.23.3)
> Requirement already satisfied: cython in /usr/local/lib64/python3.10/site-packages (from audioowl->mixingbear) (0.29.34)
> Requirement already satisfied: resampy>=0.1.2 in ./.local/lib/python3.10/site-packages (from librosa<0.5.2,>=0.5.1->audioowl->mixingbear) (0.4.2)
> Requirement already satisfied: joblib>=0.7.0 in ./.local/lib/python3.10/site-packages (from librosa<0.5.2,>=0.5.1->audioowl->mixingbear) (1.2.0)
> Requirement already satisfied: decorator>=3.0.0 in /usr/lib/python3.10/site-packages (from librosa<0.5.2,>=0.5.1->audioowl->mixingbear) (5.1.1)
> Requirement already satisfied: audioread>=2.0.0 in ./.local/lib/python3.10/site-packages (from librosa<0.5.2,>=0.5.1->audioowl->mixingbear) (3.0.0)
> Requirement already satisfied: six>=1.3 in /usr/lib/python3.10/site-packages (from librosa<0.5.2,>=0.5.1->audioowl->mixingbear) (1.16.0)
> Requirement already satisfied: scikit-learn>=0.14.0 in ./.local/lib/python3.10/site-packages (from librosa<0.5.2,>=0.5.1->audioowl->mixingbear) (1.2.2)
> Requirement already satisfied: numba>=0.53 in ./.local/lib/python3.10/site-packages (from resampy>=0.1.2->librosa<0.5.2,>=0.5.1->audioowl->mixingbear) (0.56.3)
> Requirement already satisfied: threadpoolctl>=2.0.0 in ./.local/lib/python3.10/site-packages (from scikit-learn>=0.14.0->librosa<0.5.2,>=0.5.1->audioowl->mixingbear) (3.1.0)
> Requirement already satisfied: setuptools in /usr/local/lib/python3.10/site-packages (from numba>=0.53->resampy>=0.1.2->librosa<0.5.2,>=0.5.1->audioowl->mixingbear) (65.6.3)
> Requirement already satisfied: llvmlite<0.40,>=0.39.0dev0 in ./.local/lib/python3.10/site-packages (from numba>=0.53->resampy>=0.1.2->librosa<0.5.2,>=0.5.1->audioowl->mixingbear) (0.39.1)
> Building wheels for collected packages: madmom
>   Building wheel for madmom (setup.py) ... error
>   error: subprocess-exited-with-error
>   
>   × python setup.py bdist_wheel did not run successfully.
>   │ exit code: 1
>   ╰─> [348 lines of output]

### Information about installed software

python3-3.10.10-1.fc36.x86_64
python3-Cython-0.29.26-2.fc36.x86_64

Same result on a different system:

python3-3.7.9-1.fc31.x86_64
python3-Cython-0.29.13-2.fc31.x86_64

Aka, standard Fedora system packages, across a pretty wide range of Fedora versions.  I switched then to the pip cython versions:

Cython-0.29.34-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl

But same problem.

**Comment by enn-nafnlaus** [comment]
Odd.  madmom==0.16.1 installs successfully. But for some reason, mixingbear is refusing to use it, despite requiring "madmom<0.15.2,>=0.15.1"

>  ~]$ pip install mixingbear
> Defaulting to user installation because normal site-packages is not writeable
> Collecting mixingbear
>   Using cached mixingbear-0.0.1-py3-none-any.whl
> Requirement already satisfied: pydub<0.20.1,>=0.20.0 in ./.local/lib/python3.10/site-packages (from mixingbear) (0.20.0)
> Requirement already satisfied: cython in /usr/local/lib64/python3.10/site-packages (from audioowl->mixingbear) (0.29.34)
> Collecting madmom<0.15.2,>=0.15.1
>   Using cached madmom-0.15.1.tar.gz (15.7 MB)
>   Preparing metadata (setup.py) ... done
> Requirement already satisfied: scipy in /usr/lib64/python3.10/site-packages (from audioowl->mixingbear) (1.8.1)
> Requirement already satisfied: numpy in ./.local/lib/python3.10/site-packages (from audioowl->mixingbear) (1.23.3)
> Collecting librosa<0.5.2,>=0.5.1
>   Using cached librosa-0.5.1-py3-none-any.whl
> Requirement already satisfied: six>=1.3 in /usr/lib/python3.10/site-packages (from librosa<0.5.2,>=0.5.1->audioowl->mixingbear) (1.16.0)
> Requirement already satisfied: audioread>=2.0.0 in ./.local/lib/python3.10/site-packages (from librosa<0.5.2,>=0.5.1->audioowl->mixingbear) (3.0.0)
> Requirement already satisfied: scikit-learn>=0.14.0 in ./.local/lib/python3.10/site-packages (from librosa<0.5.2,>=0.5.1->audioowl->mixingbear) (1.2.2)
> Requirement already satisfied: resampy>=0.1.2 in ./.local/lib/python3.10/site-packages (from librosa<0.5.2,>=0.5.1->audioowl->mixingbear) (0.4.2)
> Requirement already satisfied: joblib>=0.7.0 in ./.local/lib/python3.10/site-packages (from librosa<0.5.2,>=0.5.1->audioowl->mixingbear) (1.2.0)
> Requirement already satisfied: decorator>=3.0.0 in /usr/lib/python3.10/site-packages (from librosa<0.5.2,>=0.5.1->audioowl->mixingbear) (5.1.1)
> Requirement already satisfied: numba>=0.53 in ./.local/lib/python3.10/site-packages (from resampy>=0.1.2->librosa<0.5.2,>=0.5.1->audioowl->mixingbear) (0.56.3)
> Requirement already satisfied: threadpoolctl>=2.0.0 in ./.local/lib/python3.10/site-packages (from scikit-learn>=0.14.0->librosa<0.5.2,>=0.5.1->audioowl->mixingbear) (3.1.0)
> Requirement already satisfied: setuptools in /usr/local/lib/python3.10/site-packages (from numba>=0.53->resampy>=0.1.2->librosa<0.5.2,>=0.5.1->audioowl->mixingbear) (65.6.3)
> Requirement already satisfied: llvmlite<0.40,>=0.39.0dev0 in ./.local/lib/python3.10/site-packages (from numba>=0.53->resampy>=0.1.2->librosa<0.5.2,>=0.5.1->audioowl->mixingbear) (0.39.1)
> Building wheels for collected packages: madmom
>   Building wheel for madmom (setup.py) ... -

Well, not your issue then!

**Comment by superbock** [comment]
I'll close it then, please feel free to re-open it if needed.
